//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy
{
    using Gr4vy.Models.Components;
    using Gr4vy.Models.Errors;
    using Gr4vy.Utils;
    using System;

    public interface IAccountUpdater
    {
        public IJobs Jobs { get; }
    }

    public class AccountUpdater: IAccountUpdater
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// Jobs SubSDK.
        /// <see cref="IJobs"/>
        /// </summary>
        public IJobs Jobs { get; private set; }

        public AccountUpdater(SDKConfig config)
        {
            SDKConfiguration = config;
            Jobs = new Jobs(SDKConfiguration);
        }
    }
}