//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class AccountUpdaterOptions
    {
        /// <summary>
        /// The type of response to simulate.
        /// </summary>
        [JsonProperty("response_code")]
        public string? ResponseCode { get; } = "updated";

        /// <summary>
        /// When the `response_code` is set to `updated`, the payment method's account number will be updated to this value.
        /// </summary>
        [JsonProperty("account_number")]
        public string? AccountNumber { get; set; } = null;

        /// <summary>
        /// When the `response_code` is set to `updated`, the payment method's expiration month will be updated to this value.
        /// </summary>
        [JsonProperty("expiration_month")]
        public string? ExpirationMonth { get; set; } = null;

        /// <summary>
        /// When the `response_code` is set to `updated`, the payment method's expiration year will be updated to this value.
        /// </summary>
        [JsonProperty("expiration_year")]
        public string? ExpirationYear { get; set; } = null;

        /// <summary>
        /// The type of error code to simulate.
        /// </summary>
        [JsonProperty("error_code")]
        public string? ErrorCode { get; set; } = null;
    }
}