//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public class AccountUpdaterJob
    {
        /// <summary>
        /// Always `account-updater-job`
        /// </summary>
        [JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string Type { get; } = "account-updater-job";

        /// <summary>
        /// The ID for the account updater job.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The ID of the merchant account this job belongs to.
        /// </summary>
        [JsonProperty("merchant_account_id", Required = Newtonsoft.Json.Required.Always)]
        public string MerchantAccountId { get; set; } = default!;

        /// <summary>
        /// A list of the payment methods that have been scheduled for an update.
        /// </summary>
        [JsonProperty("inquiries", Required = Newtonsoft.Json.Required.Always)]
        public List<AccountUpdaterInquirySummary> Inquiries { get; set; } = default!;

        /// <summary>
        /// The date and time when this payment method was first created in our system.
        /// </summary>
        [JsonProperty("created_at", Required = Newtonsoft.Json.Required.Always)]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// The date and time when this payment method was last updated in our system.
        /// </summary>
        [JsonProperty("updated_at", Required = Newtonsoft.Json.Required.Always)]
        public DateTime UpdatedAt { get; set; } = default!;
    }
}