//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class AdyenPixRecurringOptions
    {
        /// <summary>
        /// The frequency at which the shopper will be charged. Possible values: weekly, monthly, quarterly, half-yearly, and yearly.
        /// </summary>
        [JsonProperty("frequency", NullValueHandling = NullValueHandling.Include)]
        public string? Frequency
        {
            get => _frequency;
            set
            {
                _frequency = value;
                _frequencySet = true;
            }
        }

        private string? _frequency = null;

        private bool _frequencySet = false;

        public bool ShouldSerializeFrequency() => _frequencySet;

        /// <summary>
        /// For a billing plan where the payment amount is fixed, the currency and value for each recurring payment.
        /// </summary>
        [JsonProperty("recurringAmount", NullValueHandling = NullValueHandling.Include)]
        public AdyenPixRecurringAmount? RecurringAmount { get; set; }

        /// <summary>
        /// Start date of the billing plan, in YYYY-MM-DD format.
        /// </summary>
        [JsonProperty("startsAt", NullValueHandling = NullValueHandling.Include)]
        public string? StartsAt
        {
            get => _startsAt;
            set
            {
                _startsAt = value;
                _startsAtSet = true;
            }
        }

        private string? _startsAt = null;

        private bool _startsAtSet = false;

        public bool ShouldSerializeStartsAt() => _startsAtSet;

        /// <summary>
        /// End date of the billing plan, in YYYY-MM-DD format. The end date must align with the frequency and the start date of the billing plan. If left blank, the subscription will continue indefinitely unless it is cancelled by the shopper.
        /// </summary>
        [JsonProperty("endsAt", NullValueHandling = NullValueHandling.Include)]
        public string? EndsAt
        {
            get => _endsAt;
            set
            {
                _endsAt = value;
                _endsAtSet = true;
            }
        }

        private string? _endsAt = null;

        private bool _endsAtSet = false;

        public bool ShouldSerializeEndsAt() => _endsAtSet;

        /// <summary>
        /// The text that that will be shown on the shopper's bank statement for the recurring payments. We recommend to add a descriptive text about the subscription to let your shoppers recognize your recurring payments.
        /// </summary>
        [JsonProperty("recurringStatement", NullValueHandling = NullValueHandling.Include)]
        public string? RecurringStatement
        {
            get => _recurringStatement;
            set
            {
                _recurringStatement = value;
                _recurringStatementSet = true;
            }
        }

        private string? _recurringStatement = null;

        private bool _recurringStatementSet = false;

        public bool ShouldSerializeRecurringStatement() => _recurringStatementSet;
    }
}