//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class AdyenSepaOptions
    {

        /// <summary>
        /// Set to `true` to enable Auto Rescue for a transaction. Use the `maxDaysToRescue` to specify a rescue window.
        /// </summary>
        [JsonProperty("autoRescue")]
        public bool? AutoRescue { get; set; } = null;

        /// <summary>
        /// The rescue window for a transaction, in days, when `autoRescue` is set to `true`. You can specify a value between 1 and 48. For cards, the default is one calendar month. For SEPA, the default is 42 days.
        /// </summary>
        [JsonProperty("maxDaysToRescue")]
        public long? MaxDaysToRescue { get; set; } = null;

        /// <summary>
        /// Passes additional data to the Adyen API when creating a transaction.
        /// </summary>
        [JsonProperty("additionalData")]
        public Dictionary<string, string>? AdditionalData { get; set; } = null;

        /// <summary>
        /// The rescue scenario to simulate for a transaction, when `autoRescue` is set to `true`.
        /// </summary>
        [JsonProperty("autoRescueSepaScenario")]
        public string? AutoRescueSepaScenario { get; set; } = null;

        /// <summary>
        /// The name on the SEPA bank account.
        /// </summary>
        [JsonProperty("ownerName")]
        public string? OwnerName { get; set; } = null;
    }
}