//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class AdyenSplitsOptions
    {
        /// <summary>
        /// Split payment values to pass to the Adyen API on payment authorization. See <a href="https://docs.adyen.com/platforms/online-payments/split-transactions/split-payments-at-authorization/">the Adyen docs</a> for details on the format and contents of the list.
        /// </summary>
        [JsonProperty("authorization")]
        public List<Dictionary<string, object>>? Authorization { get; set; } = null;

        /// <summary>
        /// Split payment values to pass to the Adyen API on payment capture. See <a href="https://docs.adyen.com/platforms/online-payments/split-transactions/split-payments-at-capture/">the Adyen docs</a> for details on the format and contents of the list.
        /// </summary>
        [JsonProperty("capture")]
        public List<Dictionary<string, object>>? Capture { get; set; } = null;

        /// <summary>
        /// Split payment values to pass to the Adyen API on payment refund. See <a href="https://docs.adyen.com/platforms/online-payments/split-transactions/split-refunds/">the Adyen docs</a> for details on the format and contents of the list.
        /// </summary>
        [JsonProperty("refund")]
        public List<Dictionary<string, object>>? Refund { get; set; } = null;
    }
}