//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class AdyenPixOptions
    {
        /// <summary>
        /// Passes additional data to the Adyen API when creating a transaction.
        /// </summary>
        [JsonProperty("additionalData", NullValueHandling = NullValueHandling.Include)]
        public Dictionary<string, string>? AdditionalData
        {
            get => _additionalData;
            set
            {
                _additionalData = value;
                _additionalDataSet = true;
            }
        }

        private Dictionary<string, string>? _additionalData = null;

        private bool _additionalDataSet = false;

        public bool ShouldSerializeAdditionalData() => _additionalDataSet;

        /// <summary>
        /// Passes `pixRecurring` data to Adyen.
        /// </summary>
        [JsonProperty("pixRecurring", NullValueHandling = NullValueHandling.Include)]
        public AdyenPixRecurringOptions? PixRecurring
        {
            get => _pixRecurring;
            set
            {
                _pixRecurring = value;
                _pixRecurringSet = true;
            }
        }

        private AdyenPixRecurringOptions? _pixRecurring = null;

        private bool _pixRecurringSet = false;

        public bool ShouldSerializePixRecurring() => _pixRecurringSet;
    }
}