//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class AffirmOptions
    {

        /// <summary>
        /// Passes additional discounts to the Affirm widget.
        /// </summary>
        [JsonProperty("discounts")]
        public Dictionary<string, Dictionary<string, object>>? Discounts { get; set; } = null;

        /// <summary>
        /// Passes itinerary data to the Affirm API.
        /// </summary>
        [JsonProperty("itinerary")]
        public AffirmItineraryOptions? Itinerary { get; set; } = null;
    }
}