//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class AuditLogAction : IEquatable<AuditLogAction>, IOpenEnum<string>
    {
        public static readonly AuditLogAction Created = new AuditLogAction("created");
        public static readonly AuditLogAction Updated = new AuditLogAction("updated");
        public static readonly AuditLogAction Deleted = new AuditLogAction("deleted");
        public static readonly AuditLogAction Voided = new AuditLogAction("voided");
        public static readonly AuditLogAction Canceled = new AuditLogAction("canceled");
        public static readonly AuditLogAction Captured = new AuditLogAction("captured");

        private static readonly Dictionary <string, AuditLogAction> _knownValues =
            new Dictionary <string, AuditLogAction> ()
            {
                ["created"] = Created,
                ["updated"] = Updated,
                ["deleted"] = Deleted,
                ["voided"] = Voided,
                ["canceled"] = Canceled,
                ["captured"] = Captured
            };

        private static readonly ConcurrentDictionary<string, AuditLogAction> _values =
            new ConcurrentDictionary<string, AuditLogAction>(_knownValues);

        private AuditLogAction(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static AuditLogAction Of(string value)
        {
            return _values.GetOrAdd(value, _ => new AuditLogAction(value));
        }

        public static implicit operator AuditLogAction(string value) => Of(value);
        public static implicit operator string(AuditLogAction auditlogaction) => auditlogaction.Value;

        public static AuditLogAction[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as AuditLogAction);

        public bool Equals(AuditLogAction? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}