//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum AuditLogAction
    {
        [JsonProperty("created")]
        Created,
        [JsonProperty("updated")]
        Updated,
        [JsonProperty("deleted")]
        Deleted,
        [JsonProperty("voided")]
        Voided,
        [JsonProperty("captured")]
        Captured,
    }

    public static class AuditLogActionExtension
    {
        public static string Value(this AuditLogAction value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AuditLogAction ToEnum(this string value)
        {
            foreach(var field in typeof(AuditLogAction).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AuditLogAction)
                    {
                        return (AuditLogAction)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AuditLogAction");
        }
    }

}