//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Merchant provided browser info
    /// </summary>
    public class BrowserInfo
    {

        [JsonProperty("javascript_enabled")]
        public bool JavascriptEnabled { get; set; } = default!;

        [JsonProperty("java_enabled")]
        public bool JavaEnabled { get; set; } = default!;

        [JsonProperty("language")]
        public string Language { get; set; } = default!;

        [JsonProperty("color_depth")]
        public long ColorDepth { get; set; } = default!;

        [JsonProperty("screen_height")]
        public long ScreenHeight { get; set; } = default!;

        [JsonProperty("screen_width")]
        public long ScreenWidth { get; set; } = default!;

        [JsonProperty("time_zone_offset")]
        public long TimeZoneOffset { get; set; } = default!;

        /// <summary>
        /// Exact content of the HTTP user-agent header.
        /// </summary>
        [JsonProperty("user_agent")]
        public string UserAgent { get; set; } = default!;

        /// <summary>
        /// The platform that is being used to access the website.
        /// </summary>
        [JsonProperty("user_device")]
        public string UserDevice { get; set; } = default!;

        /// <summary>
        /// The Accept header of the request from the buyer&apos;s browser.
        /// </summary>
        [JsonProperty("accept_header")]
        public string? AcceptHeader { get; set; } = null;
    }
}