//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Components
{
    using Newtonsoft.Json;
    using gr4vy.Models.Components;
    using gr4vy.Utils;
    
    /// <summary>
    /// Request body for updating an existing buyer
    /// </summary>
    public class BuyerUpdate
    {

        /// <summary>
        /// The display name for the buyer.
        /// </summary>
        [JsonProperty("display_name")]
        public string? DisplayName { get; set; } = null;

        /// <summary>
        /// The merchant identifier for this buyer.
        /// </summary>
        [JsonProperty("external_identifier")]
        public string? ExternalIdentifier { get; set; } = null;

        /// <summary>
        /// The buyer account number
        /// </summary>
        [JsonProperty("account_number")]
        public string? AccountNumber { get; set; } = null;

        /// <summary>
        /// The billing name, address, email, and other fields for this buyer.
        /// </summary>
        [JsonProperty("billing_details")]
        public BillingDetailsInput? BillingDetails { get; set; } = null;
    }
}