//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class CheckoutSessionPaymentMethodCreate
    {
        /// <summary>
        /// Always `checkout-session`
        /// </summary>
        [JsonProperty("method", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string Method { get; } = "checkout-session";

        /// <summary>
        /// The ID for the checkout session.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The merchant reference that can be used to match the payment method against your own records.
        /// </summary>
        [JsonProperty("external_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> ExternalIdentifier { get; set; }
        public bool ShouldSerializeExternalIdentifier() => ExternalIdentifier.IsSet;

        /// <summary>
        /// The `id` of a stored buyer to use Use this instead of the `buyer_external_identifier`.
        /// </summary>
        [JsonProperty("buyer_id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BuyerId { get; set; }
        public bool ShouldSerializeBuyerId() => BuyerId.IsSet;

        /// <summary>
        /// The `external_identifier` of a stored buyer to use. Use this instead of the `buyer_id`.
        /// </summary>
        [JsonProperty("buyer_external_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BuyerExternalIdentifier { get; set; }
        public bool ShouldSerializeBuyerExternalIdentifier() => BuyerExternalIdentifier.IsSet;
    }
}