//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    
    public class ClickToPaySession
    {

        /// <summary>
        /// The ID of the Click to Pay application.
        /// </summary>
        [JsonProperty("digital_payment_application_id")]
        public string DigitalPaymentApplicationId { get; set; } = default!;

        /// <summary>
        /// The merchant name as configured ont he the Click to Pay wallet.
        /// </summary>
        [JsonProperty("digital_payment_application_name")]
        public string DigitalPaymentApplicationName { get; set; } = default!;
    }
}