//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using gr4vy.Utils;
    
    public enum CreateSessionStatus
    {
        [JsonProperty("succeeded")]
        Succeeded,
        [JsonProperty("failed")]
        Failed,
    }

    public static class CreateSessionStatusExtension
    {
        public static string Value(this CreateSessionStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CreateSessionStatus ToEnum(this string value)
        {
            foreach(var field in typeof(CreateSessionStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CreateSessionStatus)
                    {
                        return (CreateSessionStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CreateSessionStatus");
        }
    }

}