//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Components
{
    using Newtonsoft.Json;
    using gr4vy.Utils;
    
    public class Cryptogram
    {

        /// <summary>
        /// Always `network-token-cryptogram`.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; } = "network-token-cryptogram";

        /// <summary>
        /// The cryptogram of the network token.
        /// </summary>
        [JsonProperty("cryptogram")]
        public string CryptogramValue { get; set; } = default!;
    }
}