//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Components
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using gr4vy.Models.Components;
    using gr4vy.Utils;
    
    public class DigitalWallet
    {

        /// <summary>
        /// Always `digital-wallet`.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; } = "digital-wallet";

        /// <summary>
        /// The ID for the digital wallet.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The ID of the merchant account this digital wallet belongs to.
        /// </summary>
        [JsonProperty("merchant_account_id")]
        public string MerchantAccountId { get; set; } = default!;

        [JsonProperty("provider")]
        public DigitalWalletProvider Provider { get; set; } = default!;

        /// <summary>
        /// The name of the merchant the digital wallet is registered to.
        /// </summary>
        [JsonProperty("merchant_name")]
        public string MerchantName { get; set; } = default!;

        /// <summary>
        /// The consumer facing name of the merchant.
        /// </summary>
        [JsonProperty("merchant_display_name")]
        public string? MerchantDisplayName { get; set; } = null;

        /// <summary>
        /// The main URL of the merchant.
        /// </summary>
        [JsonProperty("merchant_url")]
        public string? MerchantUrl { get; set; } = null;

        /// <summary>
        /// The country code where the merchant is registered.
        /// </summary>
        [JsonProperty("merchant_country_code")]
        public string? MerchantCountryCode { get; set; } = null;

        /// <summary>
        /// The list of domain names that a digital wallet can be used on (deprecated).
        /// </summary>
        [JsonProperty("domain_names")]
        public List<string> DomainNames { get; set; } = default!;

        /// <summary>
        /// The number of active custom certificates registered for this digital wallet (Apple Pay only).
        /// </summary>
        [JsonProperty("active_certificate_count")]
        public long? ActiveCertificateCount { get; set; } = 0;

        /// <summary>
        /// The number of pending custom certificates registered for this digital wallet (Apple Pay only).
        /// </summary>
        [JsonProperty("pending_certificate_count")]
        public long? PendingCertificateCount { get; set; } = 0;

        /// <summary>
        /// The number of expired custom certificates registered for this digital wallet (Apple Pay only).
        /// </summary>
        [JsonProperty("expired_certificate_count")]
        public long? ExpiredCertificateCount { get; set; } = 0;

        /// <summary>
        /// Custom attributes for some digital wallets. Currently only used by Click to Pay.
        /// </summary>
        [JsonProperty("fields")]
        public Dictionary<string, object>? Fields { get; set; } = null;

        /// <summary>
        /// The date this buyer was created at.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// The date this buyer was last updated at.
        /// </summary>
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; } = default!;
    }
}