//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class DigitalWalletAddress
    {
        /// <summary>
        /// The first line of the address.
        /// </summary>
        [JsonProperty("line1", Required = Newtonsoft.Json.Required.Always)]
        public string Line1 { get; set; } = default!;

        /// <summary>
        /// The second line of the address.
        /// </summary>
        [JsonProperty("line2", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> Line2 { get; set; }
        public bool ShouldSerializeLine2() => Line2.IsSet;

        /// <summary>
        /// The city for the address.
        /// </summary>
        [JsonProperty("city", Required = Newtonsoft.Json.Required.Always)]
        public string City { get; set; } = default!;

        /// <summary>
        /// The code of state, county, or province for the address in ISO 3166-2 format.
        /// </summary>
        [JsonProperty("state_code", Required = Newtonsoft.Json.Required.Always)]
        public string StateCode { get; set; } = default!;

        /// <summary>
        /// The zip or postal code for the address.
        /// </summary>
        [JsonProperty("postal_code", Required = Newtonsoft.Json.Required.Always)]
        public string PostalCode { get; set; } = default!;
    }
}