//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class DlocalPIXOptions
    {
        /// <summary>
        /// Passes `subscription` data to the dLocal API for those connectors that need it.
        /// </summary>
        [JsonProperty("subscription")]
        public DlocalPIXSubscriptionOptions? Subscription { get; set; } = null;

        /// <summary>
        /// Defines scheduled payment start date. Must be provided in ISO 8601 format `(YYYY-MM-DD`). If not specified, The default is 2 days in the future.
        /// </summary>
        [JsonProperty("scheduled_date")]
        public string? ScheduledDate { get; set; } = null;
    }
}