//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class DlocalWalletOptions
    {
        /// <summary>
        /// Passes `wallet.name` to the dLocal API for those connectors that need it.
        /// </summary>
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> Name { get; set; }
        public bool ShouldSerializeName() => Name.IsSet;

        /// <summary>
        /// Passes `wallet.email` to the dLocal API for those connectors that need it.
        /// </summary>
        [JsonProperty("email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> Email { get; set; }
        public bool ShouldSerializeEmail() => Email.IsSet;

        /// <summary>
        /// Passes `wallet.token` to the dLocal API for those connectors that need it.
        /// </summary>
        [JsonProperty("token", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> Token { get; set; }
        public bool ShouldSerializeToken() => Token.IsSet;

        /// <summary>
        /// Passes `wallet.username` to the dLocal API for those connectors that need it.
        /// </summary>
        [JsonProperty("username", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> Username { get; set; }
        public bool ShouldSerializeUsername() => Username.IsSet;

        /// <summary>
        /// Passes `wallet.verify` to the dLocal API for those connectors that need it.
        /// </summary>
        [JsonProperty("verify", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<bool?> Verify { get; set; }
        public bool ShouldSerializeVerify() => Verify.IsSet;
    }
}