//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class DlocalPIXSubscriptionAmountOptions
    {
        /// <summary>
        /// Indicates the amount type unit for the subscription. Allowed values are: `FIXED`, `VARIABLE`.
        /// </summary>
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; set; } = default!;

        /// <summary>
        /// Fixed subscription amount in local currency. Required only for fixed amount subscriptions depending on the payment method.
        /// </summary>
        [JsonProperty("value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> Value { get; set; }
        public bool ShouldSerializeValue() => Value.IsSet;

        /// <summary>
        /// Minimum payer enrollment limit, not minimum recurring charge amount.
        /// </summary>
        [JsonProperty("min_value", Required = Newtonsoft.Json.Required.AllowNull, NullValueHandling = NullValueHandling.Include)]
        public string? MinValue { get; set; }
    }
}