//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class EcommpayOptions
    {
        /// <summary>
        /// The start date of the booking in ISO 8601 format (YYYY-MM-DD). Required for certain MCCs.
        /// </summary>
        [JsonProperty("booking_start_date", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BookingStartDate { get; set; }
        public bool ShouldSerializeBookingStartDate() => BookingStartDate.IsSet;

        /// <summary>
        /// The end date of the booking in ISO 8601 format (YYYY-MM-DD). Required for certain MCCs.
        /// </summary>
        [JsonProperty("booking_end_date", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BookingEndDate { get; set; }
        public bool ShouldSerializeBookingEndDate() => BookingEndDate.IsSet;
    }
}