//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class FiservInstallmentOptions
    {
        /// <summary>
        /// Passes the `order.installmentOptions.numberOfInstallments` field to the Fiserv API.
        /// </summary>
        [JsonProperty("numberOfInstallments", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<long?> NumberOfInstallments { get; set; }
        public bool ShouldSerializeNumberOfInstallments() => NumberOfInstallments.IsSet;

        /// <summary>
        /// Passes the `order.installmentOptions.installmentsInterest` field to the Fiserv API.
        /// </summary>
        [JsonProperty("installmentsInterest", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<bool?> InstallmentsInterest { get; set; }
        public bool ShouldSerializeInstallmentsInterest() => InstallmentsInterest.IsSet;

        /// <summary>
        /// Passes the `order.installmentOptions.installmentDelayMonths` field to the Fiserv API.
        /// </summary>
        [JsonProperty("installmentDelayMonths", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<long?> InstallmentDelayMonths { get; set; }
        public bool ShouldSerializeInstallmentDelayMonths() => InstallmentDelayMonths.IsSet;

        /// <summary>
        /// Passes the `order.installmentOptions.merchantAdviceCodeSupported` field to the Fiserv API.
        /// </summary>
        [JsonProperty("merchantAdviceCodeSupported", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<bool?> MerchantAdviceCodeSupported { get; set; }
        public bool ShouldSerializeMerchantAdviceCodeSupported() => MerchantAdviceCodeSupported.IsSet;
    }
}