//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class ForterAntiFraudOptionsCartItem
    {
        /// <summary>
        /// Basic information about the cart item.
        /// </summary>
        [JsonProperty("basic_item_data", NullValueHandling = NullValueHandling.Include)]
        public ForterAntiFraudOptionsCartItemBasicItemData? BasicItemData
        {
            get => _basicItemData;
            set
            {
                _basicItemData = value;
                _basicItemDataSet = true;
            }
        }

        private ForterAntiFraudOptionsCartItemBasicItemData? _basicItemData = null;

        private bool _basicItemDataSet = false;

        public bool ShouldSerializeBasicItemData() => _basicItemDataSet;

        /// <summary>
        /// Details about how the item will be delivered.
        /// </summary>
        [JsonProperty("delivery_details", NullValueHandling = NullValueHandling.Include)]
        public ForterAntiFraudOptionsCartItemDeliveryDetails? DeliveryDetails
        {
            get => _deliveryDetails;
            set
            {
                _deliveryDetails = value;
                _deliveryDetailsSet = true;
            }
        }

        private ForterAntiFraudOptionsCartItemDeliveryDetails? _deliveryDetails = null;

        private bool _deliveryDetailsSet = false;

        public bool ShouldSerializeDeliveryDetails() => _deliveryDetailsSet;

        /// <summary>
        /// List of beneficiaries who will receive this item.
        /// </summary>
        [JsonProperty("beneficiaries", NullValueHandling = NullValueHandling.Include)]
        public List<ForterAntiFraudOptionsCartItemBeneficiary>? Beneficiaries
        {
            get => _beneficiaries;
            set
            {
                _beneficiaries = value;
                _beneficiariesSet = true;
            }
        }

        private List<ForterAntiFraudOptionsCartItemBeneficiary>? _beneficiaries = null;

        private bool _beneficiariesSet = false;

        public bool ShouldSerializeBeneficiaries() => _beneficiariesSet;
    }
}