//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class ForterAntiFraudOptionsCartItemBeneficiaryPhone
    {
        /// <summary>
        /// The phone number of the beneficiary.
        /// </summary>
        [JsonProperty("phone", NullValueHandling = NullValueHandling.Include)]
        public string Phone
        {
            get => _phone;
            set
            {
                _phone = value;
                _phoneSet = true;
            }
        }

        private string _phone = default!;

        private bool _phoneSet = true;

        public bool ShouldSerializePhone() => _phoneSet;
    }
}