//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class ForterAntiFraudOptionsCartItem
    {
        /// <summary>
        /// Basic information about the cart item.
        /// </summary>
        [JsonProperty("basic_item_data", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<ForterAntiFraudOptionsCartItemBasicItemData?> BasicItemData { get; set; }
        public bool ShouldSerializeBasicItemData() => BasicItemData.IsSet;

        /// <summary>
        /// Details about how the item will be delivered.
        /// </summary>
        [JsonProperty("delivery_details", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<ForterAntiFraudOptionsCartItemDeliveryDetails?> DeliveryDetails { get; set; }
        public bool ShouldSerializeDeliveryDetails() => DeliveryDetails.IsSet;

        /// <summary>
        /// List of beneficiaries who will receive this item.
        /// </summary>
        [JsonProperty("beneficiaries", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<List<ForterAntiFraudOptionsCartItemBeneficiary>?> Beneficiaries { get; set; }
        public bool ShouldSerializeBeneficiaries() => Beneficiaries.IsSet;
    }
}