//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class ForterAntiFraudOptionsCartItemBeneficiaryPersonalDetails
    {
        /// <summary>
        /// First name of the beneficiary.
        /// </summary>
        [JsonProperty("first_name", NullValueHandling = NullValueHandling.Include)]
        public string? FirstName
        {
            get => _firstName;
            set
            {
                _firstName = value;
                _firstNameSet = true;
            }
        }

        private string? _firstName = null;

        private bool _firstNameSet = false;

        public bool ShouldSerializeFirstName() => _firstNameSet;

        /// <summary>
        /// Last name of the beneficiary.
        /// </summary>
        [JsonProperty("last_name", NullValueHandling = NullValueHandling.Include)]
        public string? LastName
        {
            get => _lastName;
            set
            {
                _lastName = value;
                _lastNameSet = true;
            }
        }

        private string? _lastName = null;

        private bool _lastNameSet = false;

        public bool ShouldSerializeLastName() => _lastNameSet;

        /// <summary>
        /// Email address of the beneficiary.
        /// </summary>
        [JsonProperty("email", NullValueHandling = NullValueHandling.Include)]
        public string? Email
        {
            get => _email;
            set
            {
                _email = value;
                _emailSet = true;
            }
        }

        private string? _email = null;

        private bool _emailSet = false;

        public bool ShouldSerializeEmail() => _emailSet;
    }
}