//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// The details used to issue a new virtual gift card.
    /// </summary>
    public class GiftCardIssuanceCreate
    {
        /// <summary>
        /// The provider theme code to issue the gift card against.
        /// </summary>
        [JsonProperty("theme")]
        public string Theme { get; set; } = default!;

        /// <summary>
        /// The amount to load onto the gift card, in the smallest denomination for the currency.
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;

        /// <summary>
        /// The ISO-4217 currency code for the `amount`.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; } = default!;

        /// <summary>
        /// An optional external identifier for this issuance.
        /// </summary>
        [JsonProperty("external_identifier")]
        public string? ExternalIdentifier { get; set; } = null;
    }
}