//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class GiftCardCreate
    {
        /// <summary>
        /// The 16-19 digit number for the gift card.
        /// </summary>
        [JsonProperty("number", Required = Newtonsoft.Json.Required.Always)]
        public string Number { get; set; } = default!;

        /// <summary>
        /// The PIN for this gift card.
        /// </summary>
        [JsonProperty("pin", Required = Newtonsoft.Json.Required.Always)]
        public string Pin { get; set; } = default!;

        /// <summary>
        /// The ID of the buyer to associate this gift card to. If this field is provided then the `buyer_external_identifier` field needs to be unset.
        /// </summary>
        [JsonProperty("buyer_id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BuyerId { get; set; }
        public bool ShouldSerializeBuyerId() => BuyerId.IsSet;

        /// <summary>
        /// The `external_identifier` of the buyer to associate this gift card to. If this field is provided then the `buyer_id` field needs to be unset.
        /// </summary>
        [JsonProperty("buyer_external_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BuyerExternalIdentifier { get; set; }
        public bool ShouldSerializeBuyerExternalIdentifier() => BuyerExternalIdentifier.IsSet;
    }
}