//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Create a charge against a gift card
    /// </summary>
    public class GiftCardTransactionCreate
    {

        /// <summary>
        /// The 16-19 digit number for the gift card.
        /// </summary>
        [JsonProperty("number")]
        public string Number { get; set; } = default!;

        /// <summary>
        /// The PIN for this gift card.
        /// </summary>
        [JsonProperty("pin")]
        public string Pin { get; set; } = default!;

        /// <summary>
        /// The monetary amount for this transaction to charge against the gift card, in the smallest currency unit for the given currency, for example `1299` cents to create an authorization for `$12.99`.
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;
    }
}