//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class GiftCardTokenTransactionCreate
    {
        /// <summary>
        /// The ID for the gift card to charge.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The monetary amount for this transaction to charge against the gift card, in the smallest currency unit (for example, cents or pence).
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;
    }
}