//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Components
{
    using Newtonsoft.Json;
    using gr4vy.Utils;
    
    public class GooglePaySession
    {

        /// <summary>
        /// The gateway ID for the merchant as assigned by our platform.
        /// </summary>
        [JsonProperty("gateway_merchant_id")]
        public string GatewayMerchantId { get; set; } = default!;

        /// <summary>
        /// The session token for Google Pay.
        /// </summary>
        [JsonProperty("token")]
        public string Token { get; set; } = default!;
    }
}