//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class GuestBuyer
    {
        /// <summary>
        /// The display name for the buyer.
        /// </summary>
        [JsonProperty("display_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> DisplayName { get; set; }
        public bool ShouldSerializeDisplayName() => DisplayName.IsSet;

        /// <summary>
        /// The merchant identifier for this buyer.
        /// </summary>
        [JsonProperty("external_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> ExternalIdentifier { get; set; }
        public bool ShouldSerializeExternalIdentifier() => ExternalIdentifier.IsSet;

        /// <summary>
        /// The billing name, address, email, and other fields for this buyer.
        /// </summary>
        [JsonProperty("billing_details", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<BillingDetails?> BillingDetails { get; set; }
        public bool ShouldSerializeBillingDetails() => BillingDetails.IsSet;

        /// <summary>
        /// The buyer account number.
        /// </summary>
        [JsonProperty("account_number", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> AccountNumber { get; set; }
        public bool ShouldSerializeAccountNumber() => AccountNumber.IsSet;

        /// <summary>
        /// The optional shipping details for this buyer.
        /// </summary>
        [JsonProperty("shipping_details", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<ShippingDetailsCreate?> ShippingDetails { get; set; }
        public bool ShouldSerializeShippingDetails() => ShippingDetails.IsSet;
    }
}