//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class KlarnaOptions
    {
        /// <summary>
        /// Provides subscription information to Klarna.
        /// </summary>
        [JsonProperty("subscription", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<KlarnaSubscriptionOptions?> Subscription { get; set; }
        public bool ShouldSerializeSubscription() => Subscription.IsSet;

        /// <summary>
        /// When set to `true`, this will authorize the transaction with Klarna for the purposes of tokenizing the payment method with the transaction details. No funds will be captured and the authorization will be automatically voided. This is useful for up-sell scenarios where you want to tokenize a Klarna payment method for future use.
        /// </summary>
        [JsonProperty("token_only_mode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<bool?> TokenOnlyMode { get; set; }
        public bool ShouldSerializeTokenOnlyMode() => TokenOnlyMode.IsSet;

        /// <summary>
        /// An authorization token returned by the Klarna Express Checkout JS SDK after the buyer completes payment in the embedded widget. When provided, the connector skips the HPP redirect and places the Klarna order directly using this token.
        /// </summary>
        [JsonProperty("authorization_token", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> AuthorizationToken { get; set; }
        public bool ShouldSerializeAuthorizationToken() => AuthorizationToken.IsSet;
    }
}