//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public class MerchantAccountThreeDSConfiguration
    {
        /// <summary>
        /// Acquirer BIN to use when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_acquirer_bin")]
        public string MerchantAcquirerBin { get; set; } = default!;

        /// <summary>
        /// Merchant ID to use when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_acquirer_id")]
        public string MerchantAcquirerId { get; set; } = default!;

        [JsonProperty("merchant_name")]
        public string MerchantName { get; set; } = default!;

        /// <summary>
        /// The merchant's ISO 3166-1 numeric country code.
        /// </summary>
        [JsonProperty("merchant_country_code")]
        public string MerchantCountryCode { get; set; } = default!;

        /// <summary>
        /// Merchant category code to use when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_category_code")]
        public string MerchantCategoryCode { get; set; } = default!;

        /// <summary>
        /// URL to send when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_url")]
        public string MerchantUrl { get; set; } = default!;

        /// <summary>
        /// Always `merchant-account.three-ds-configuration`.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; } = "merchant-account.three-ds-configuration";

        /// <summary>
        /// Unique identifier for the 3DS configuration.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// ID of the associated merchant account.
        /// </summary>
        [JsonProperty("merchant_account_id")]
        public string MerchantAccountId { get; set; } = default!;

        /// <summary>
        /// The date and time when this 3DS configuration was first created in our system.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// The date and time when this 3DS configuration was last updated in our system.
        /// </summary>
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; } = default!;

        [JsonProperty("scheme")]
        public string Scheme { get; set; } = default!;

        /// <summary>
        /// ISO 4217 currency code (3 characters). If null, the configuration applies to all currencies.
        /// </summary>
        [JsonProperty("currency", NullValueHandling = NullValueHandling.Include)]
        public string? Currency { get; set; }

        /// <summary>
        /// Additional information about the 3DS configuration, stored as key-value pairs.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata { get; set; } = default!;
    }
}