//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class MerchantAccountThreeDSConfigurationCreate
    {
        /// <summary>
        /// Acquirer BIN to use when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_acquirer_bin")]
        public string MerchantAcquirerBin { get; set; } = default!;

        /// <summary>
        /// Merchant ID to use when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_acquirer_id")]
        public string MerchantAcquirerId { get; set; } = default!;

        [JsonProperty("merchant_name")]
        public string MerchantName { get; set; } = default!;

        /// <summary>
        /// The merchant's ISO 3166-1 numeric country code.
        /// </summary>
        [JsonProperty("merchant_country_code")]
        public string MerchantCountryCode { get; set; } = default!;

        /// <summary>
        /// Merchant category code to use when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_category_code")]
        public string MerchantCategoryCode { get; set; } = default!;

        /// <summary>
        /// URL to send when calling 3DS through this scheme.
        /// </summary>
        [JsonProperty("merchant_url")]
        public string MerchantUrl { get; set; } = default!;

        [JsonProperty("scheme")]
        public string Scheme { get; set; } = default!;

        /// <summary>
        /// ISO 4217 currency code (3 characters). If left null, the configuration will apply to all currencies.
        /// </summary>
        [JsonProperty("currency")]
        public string? Currency { get; set; } = null;

        /// <summary>
        /// Any additional information about the 3DS configuration that you would like to store as key-value pairs.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string> Metadata { get; set; } = default!;
    }
}