//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class MerchantAccountUpdate
    {

        /// <summary>
        /// Whether the Real-Time Account Updater service is enabled for this merchant account. The Account Updater service is used to update card details when cards are lost, stolen or expired. If the field is not set or if it&apos;s set to `false`, the Account Updater service doesn&apos;t get called if a payment fails with expired or invalid card details. If the field is set to `true`, the service is called. Please note that for this to work the other `account_updater_* fields` must be set as well.
        /// </summary>
        [JsonProperty("account_updater_enabled")]
        public bool? AccountUpdaterEnabled { get; set; } = false;

        /// <summary>
        /// The public key used to encrypt the request to the Real-Time Account Updater service. The Account Updater service is used to update card details when cards are lost, stolen or expired. If the field is not set or if it&apos;s set to `null`, the Account Updater service doesn&apos;t get called. If the field is set, the other `account_updater_*` fields must be set as well.
        /// </summary>
        [JsonProperty("account_updater_request_encryption_key")]
        public string? AccountUpdaterRequestEncryptionKey { get; set; } = null;

        /// <summary>
        /// The ID of the key used to encrypt the request to the Real-Time Account Updater service. The Account Updater service is used to update card details when cards are lost, stolen or expired. If the field is not set or if it&apos;s set to `null`, the Account Updater service doesn&apos;t get called. If the field is set, the other `account_updater_*` fields must be set as well.
        /// </summary>
        [JsonProperty("account_updater_request_encryption_key_id")]
        public string? AccountUpdaterRequestEncryptionKeyId { get; set; } = null;

        /// <summary>
        /// The key used to decrypt the response from the Real-Time Account Updater service. The Account Updater service is used to update card details when cards are lost, stolen or expired. If the field is not set or if it&apos;s set to `null`, the Account Updater service doesn&apos;t get called. If the field is set, the other `account_updater_*` fields must be set as well.
        /// </summary>
        [JsonProperty("account_updater_response_decryption_key")]
        public string? AccountUpdaterResponseDecryptionKey { get; set; } = null;

        /// <summary>
        /// The ID of the key used to decrypt the request from the Real-Time Account Updater service. The Account Updater service is used to update card details when cards are lost, stolen or expired. If the field is not set or if it&apos;s set to `null`, the Account Updater service doesn&apos;t get called. If the field is set, the other `account_updater_*` fields must be set as well.
        /// </summary>
        [JsonProperty("account_updater_response_decryption_key_id")]
        public string? AccountUpdaterResponseDecryptionKeyId { get; set; } = null;

        /// <summary>
        /// The maximum monetary amount allowed for over-capture, in the smallest currency unit, for example `1299` cents to allow for an over-capture of `$12.99`.
        /// </summary>
        [JsonProperty("over_capture_amount")]
        public long? OverCaptureAmount { get; set; } = null;

        /// <summary>
        /// The maximum percentage allowed for over-capture, for example `25` to allow for an over-capture of `25%` of the original transaction amount.
        /// </summary>
        [JsonProperty("over_capture_percentage")]
        public long? OverCapturePercentage { get; set; } = null;

        /// <summary>
        /// Client key provided by Pagos to authenticate to the Loon API. Loon is the Account Updater service we use and if the field is not set or if it&apos;s set to null, the Account Updater service doesn&apos;t get configured. If the field is set to `null`, the other `loon_*` fields must be set to null as well.
        /// </summary>
        [JsonProperty("loon_client_key")]
        public string? LoonClientKey { get; set; } = null;

        /// <summary>
        /// Secret key provided by Pagos to authenticate to the Loon API. Loon is the Account Updater service we use and if the field is not set or if it&apos;s set to null, the Account Updater service doesn&apos;t get configured. If the field is set to `null`, the other `loon_*` fields must be set to null as well.
        /// </summary>
        [JsonProperty("loon_secret_key")]
        public string? LoonSecretKey { get; set; } = null;

        /// <summary>
        /// Card schemes accepted when creating jobs using this set of Loon API keys. Loon is the Account Updater service we use and if the field is not set or if it&apos;s set to null, the Account Updater service doesn&apos;t get configured. If the field is set to `null`, the other `loon_*` fields must be set to null as well.
        /// </summary>
        [JsonProperty("loon_accepted_schemes")]
        public List<string>? LoonAcceptedSchemes { get; set; } = null;

        /// <summary>
        /// Requestor ID provided for Visa after onboarding to use Network Tokens.
        /// </summary>
        [JsonProperty("visa_network_tokens_requestor_id")]
        public string? VisaNetworkTokensRequestorId { get; set; } = null;

        /// <summary>
        /// Application ID provided for Visa after onboarding to use Network Tokens.
        /// </summary>
        [JsonProperty("visa_network_tokens_app_id")]
        public string? VisaNetworkTokensAppId { get; set; } = null;

        /// <summary>
        /// Requestor ID provided for American Express after onboarding to use Network Tokens.
        /// </summary>
        [JsonProperty("amex_network_tokens_requestor_id")]
        public string? AmexNetworkTokensRequestorId { get; set; } = null;

        /// <summary>
        /// Application ID provided for American Express after onboarding to use Network Tokens.
        /// </summary>
        [JsonProperty("amex_network_tokens_app_id")]
        public string? AmexNetworkTokensAppId { get; set; } = null;

        /// <summary>
        /// Requestor ID provided for Mastercard after onboarding to use Network Tokens.
        /// </summary>
        [JsonProperty("mastercard_network_tokens_requestor_id")]
        public string? MastercardNetworkTokensRequestorId { get; set; } = null;

        /// <summary>
        /// Application ID provided for Mastercard after onboarding to use Network Tokens.
        /// </summary>
        [JsonProperty("mastercard_network_tokens_app_id")]
        public string? MastercardNetworkTokensAppId { get; set; } = null;

        /// <summary>
        /// The display name for the merchant account.
        /// </summary>
        [JsonProperty("display_name")]
        public string? DisplayName { get; set; } = null;

        /// <summary>
        /// An optional endpoint URL to deliver webhook notifications to.
        /// </summary>
        [JsonProperty("outbound_webhook_url")]
        public string? OutboundWebhookUrl { get; set; } = null;

        /// <summary>
        /// The optional username to use when `outbound_webhook_url` is configured and requires basic authentication.
        /// </summary>
        [JsonProperty("outbound_webhook_username")]
        public string? OutboundWebhookUsername { get; set; } = null;

        /// <summary>
        /// The optional password to use when `outbound_webhook_url` is configured and requires basic authentication
        /// </summary>
        [JsonProperty("outbound_webhook_password")]
        public string? OutboundWebhookPassword { get; set; } = null;
    }
}