//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class Method : IEquatable<Method>, IOpenEnum<string>
    {
        public static readonly Method Abitab = new Method("abitab");
        public static readonly Method Affirm = new Method("affirm");
        public static readonly Method Afterpay = new Method("afterpay");
        public static readonly Method Alipay = new Method("alipay");
        public static readonly Method Alipayhk = new Method("alipayhk");
        public static readonly Method Applepay = new Method("applepay");
        public static readonly Method Arcuspaynetwork = new Method("arcuspaynetwork");
        public static readonly Method Bacs = new Method("bacs");
        public static readonly Method Bancontact = new Method("bancontact");
        public static readonly Method Bank = new Method("bank");
        public static readonly Method Bcp = new Method("bcp");
        public static readonly Method Becs = new Method("becs");
        public static readonly Method Bitpay = new Method("bitpay");
        public static readonly Method Blik = new Method("blik");
        public static readonly Method Ach = new Method("ach");
        public static readonly Method Boleto = new Method("boleto");
        public static readonly Method Boost = new Method("boost");
        public static readonly Method Breb = new Method("breb");
        public static readonly Method Capitec = new Method("capitec");
        public static readonly Method Card = new Method("card");
        public static readonly Method Cashapp = new Method("cashapp");
        public static readonly Method Cashappafterpay = new Method("cashappafterpay");
        public static readonly Method Chaseorbital = new Method("chaseorbital");
        public static readonly Method Clearpay = new Method("clearpay");
        public static readonly Method ClickToPay = new Method("click-to-pay");
        public static readonly Method CustomPush = new Method("custom_push");
        public static readonly Method CustomRedirect = new Method("custom_redirect");
        public static readonly Method CustomTokenize = new Method("custom_tokenize");
        public static readonly Method Dana = new Method("dana");
        public static readonly Method Dcb = new Method("dcb");
        public static readonly Method Dlocal = new Method("dlocal");
        public static readonly Method Duitnow = new Method("duitnow");
        public static readonly Method Ebanx = new Method("ebanx");
        public static readonly Method Eckoh = new Method("eckoh");
        public static readonly Method Efecty = new Method("efecty");
        public static readonly Method Eps = new Method("eps");
        public static readonly Method Everydaypay = new Method("everydaypay");
        public static readonly Method Gcash = new Method("gcash");
        public static readonly Method Gem = new Method("gem");
        public static readonly Method Gemds = new Method("gemds");
        public static readonly Method GiftCard = new Method("gift-card");
        public static readonly Method Giropay = new Method("giropay");
        public static readonly Method Givingblock = new Method("givingblock");
        public static readonly Method Gocardless = new Method("gocardless");
        public static readonly Method Googlepay = new Method("googlepay");
        public static readonly Method GooglepayPanOnly = new Method("googlepay_pan_only");
        public static readonly Method Gopay = new Method("gopay");
        public static readonly Method Grabpay = new Method("grabpay");
        public static readonly Method Ideal = new Method("ideal");
        public static readonly Method Interac = new Method("interac");
        public static readonly Method Kakaopay = new Method("kakaopay");
        public static readonly Method Kcp = new Method("kcp");
        public static readonly Method Khipu = new Method("khipu");
        public static readonly Method Klarna = new Method("klarna");
        public static readonly Method Konbini = new Method("konbini");
        public static readonly Method Latitude = new Method("latitude");
        public static readonly Method Latitudeds = new Method("latitudeds");
        public static readonly Method Laybuy = new Method("laybuy");
        public static readonly Method Linepay = new Method("linepay");
        public static readonly Method Linkaja = new Method("linkaja");
        public static readonly Method Maybankqrpay = new Method("maybankqrpay");
        public static readonly Method Mercadopago = new Method("mercadopago");
        public static readonly Method Multibanco = new Method("multibanco");
        public static readonly Method Multipago = new Method("multipago");
        public static readonly Method Nequi = new Method("nequi");
        public static readonly Method Netbanking = new Method("netbanking");
        public static readonly Method NetworkToken = new Method("network-token");
        public static readonly Method Nupay = new Method("nupay");
        public static readonly Method Oney10x = new Method("oney_10x");
        public static readonly Method Oney12x = new Method("oney_12x");
        public static readonly Method Oney3x = new Method("oney_3x");
        public static readonly Method Oney4x = new Method("oney_4x");
        public static readonly Method Oney6x = new Method("oney_6x");
        public static readonly Method Onlinebankingcz = new Method("onlinebankingcz");
        public static readonly Method Onelink = new Method("onelink");
        public static readonly Method Ovo = new Method("ovo");
        public static readonly Method Oxxo = new Method("oxxo");
        public static readonly Method P24 = new Method("p24");
        public static readonly Method Pagoefectivo = new Method("pagoefectivo");
        public static readonly Method Paybybank = new Method("paybybank");
        public static readonly Method Payid = new Method("payid");
        public static readonly Method Paymaya = new Method("paymaya");
        public static readonly Method Paysquad = new Method("paysquad");
        public static readonly Method Paypal = new Method("paypal");
        public static readonly Method Paypaldirectorder = new Method("paypaldirectorder");
        public static readonly Method Paypalpaylater = new Method("paypalpaylater");
        public static readonly Method Paypay = new Method("paypay");
        public static readonly Method Payto = new Method("payto");
        public static readonly Method Payvalida = new Method("payvalida");
        public static readonly Method Paze = new Method("paze");
        public static readonly Method Picpay = new Method("picpay");
        public static readonly Method Pix = new Method("pix");
        public static readonly Method Plaid = new Method("plaid");
        public static readonly Method Pse = new Method("pse");
        public static readonly Method Rabbitlinepay = new Method("rabbitlinepay");
        public static readonly Method Razorpay = new Method("razorpay");
        public static readonly Method Rapipago = new Method("rapipago");
        public static readonly Method Redpagos = new Method("redpagos");
        public static readonly Method Scalapay = new Method("scalapay");
        public static readonly Method Sepa = new Method("sepa");
        public static readonly Method Servipag = new Method("servipag");
        public static readonly Method Seveneleven = new Method("seveneleven");
        public static readonly Method Sezzle = new Method("sezzle");
        public static readonly Method Shopeepay = new Method("shopeepay");
        public static readonly Method Singteldash = new Method("singteldash");
        public static readonly Method Smartpay = new Method("smartpay");
        public static readonly Method Sofort = new Method("sofort");
        public static readonly Method Spei = new Method("spei");
        public static readonly Method Stitch = new Method("stitch");
        public static readonly Method Swish = new Method("swish");
        public static readonly Method Stripe = new Method("stripe");
        public static readonly Method Stripedd = new Method("stripedd");
        public static readonly Method Stripetoken = new Method("stripetoken");
        public static readonly Method Tapi = new Method("tapi");
        public static readonly Method Tapifintechs = new Method("tapifintechs");
        public static readonly Method Thaiqr = new Method("thaiqr");
        public static readonly Method Touchngo = new Method("touchngo");
        public static readonly Method Truemoney = new Method("truemoney");
        public static readonly Method Trustly = new Method("trustly");
        public static readonly Method Trustlyeurope = new Method("trustlyeurope");
        public static readonly Method Upi = new Method("upi");
        public static readonly Method Venmo = new Method("venmo");
        public static readonly Method Vipps = new Method("vipps");
        public static readonly Method Waave = new Method("waave");
        public static readonly Method Webpay = new Method("webpay");
        public static readonly Method Wechat = new Method("wechat");
        public static readonly Method Wero = new Method("wero");
        public static readonly Method Yape = new Method("yape");
        public static readonly Method Zippay = new Method("zippay");

        private static readonly Dictionary <string, Method> _knownValues =
            new Dictionary <string, Method> ()
            {
                ["abitab"] = Abitab,
                ["affirm"] = Affirm,
                ["afterpay"] = Afterpay,
                ["alipay"] = Alipay,
                ["alipayhk"] = Alipayhk,
                ["applepay"] = Applepay,
                ["arcuspaynetwork"] = Arcuspaynetwork,
                ["bacs"] = Bacs,
                ["bancontact"] = Bancontact,
                ["bank"] = Bank,
                ["bcp"] = Bcp,
                ["becs"] = Becs,
                ["bitpay"] = Bitpay,
                ["blik"] = Blik,
                ["ach"] = Ach,
                ["boleto"] = Boleto,
                ["boost"] = Boost,
                ["breb"] = Breb,
                ["capitec"] = Capitec,
                ["card"] = Card,
                ["cashapp"] = Cashapp,
                ["cashappafterpay"] = Cashappafterpay,
                ["chaseorbital"] = Chaseorbital,
                ["clearpay"] = Clearpay,
                ["click-to-pay"] = ClickToPay,
                ["custom_push"] = CustomPush,
                ["custom_redirect"] = CustomRedirect,
                ["custom_tokenize"] = CustomTokenize,
                ["dana"] = Dana,
                ["dcb"] = Dcb,
                ["dlocal"] = Dlocal,
                ["duitnow"] = Duitnow,
                ["ebanx"] = Ebanx,
                ["eckoh"] = Eckoh,
                ["efecty"] = Efecty,
                ["eps"] = Eps,
                ["everydaypay"] = Everydaypay,
                ["gcash"] = Gcash,
                ["gem"] = Gem,
                ["gemds"] = Gemds,
                ["gift-card"] = GiftCard,
                ["giropay"] = Giropay,
                ["givingblock"] = Givingblock,
                ["gocardless"] = Gocardless,
                ["googlepay"] = Googlepay,
                ["googlepay_pan_only"] = GooglepayPanOnly,
                ["gopay"] = Gopay,
                ["grabpay"] = Grabpay,
                ["ideal"] = Ideal,
                ["interac"] = Interac,
                ["kakaopay"] = Kakaopay,
                ["kcp"] = Kcp,
                ["khipu"] = Khipu,
                ["klarna"] = Klarna,
                ["konbini"] = Konbini,
                ["latitude"] = Latitude,
                ["latitudeds"] = Latitudeds,
                ["laybuy"] = Laybuy,
                ["linepay"] = Linepay,
                ["linkaja"] = Linkaja,
                ["maybankqrpay"] = Maybankqrpay,
                ["mercadopago"] = Mercadopago,
                ["multibanco"] = Multibanco,
                ["multipago"] = Multipago,
                ["nequi"] = Nequi,
                ["netbanking"] = Netbanking,
                ["network-token"] = NetworkToken,
                ["nupay"] = Nupay,
                ["oney_10x"] = Oney10x,
                ["oney_12x"] = Oney12x,
                ["oney_3x"] = Oney3x,
                ["oney_4x"] = Oney4x,
                ["oney_6x"] = Oney6x,
                ["onlinebankingcz"] = Onlinebankingcz,
                ["onelink"] = Onelink,
                ["ovo"] = Ovo,
                ["oxxo"] = Oxxo,
                ["p24"] = P24,
                ["pagoefectivo"] = Pagoefectivo,
                ["paybybank"] = Paybybank,
                ["payid"] = Payid,
                ["paymaya"] = Paymaya,
                ["paysquad"] = Paysquad,
                ["paypal"] = Paypal,
                ["paypaldirectorder"] = Paypaldirectorder,
                ["paypalpaylater"] = Paypalpaylater,
                ["paypay"] = Paypay,
                ["payto"] = Payto,
                ["payvalida"] = Payvalida,
                ["paze"] = Paze,
                ["picpay"] = Picpay,
                ["pix"] = Pix,
                ["plaid"] = Plaid,
                ["pse"] = Pse,
                ["rabbitlinepay"] = Rabbitlinepay,
                ["razorpay"] = Razorpay,
                ["rapipago"] = Rapipago,
                ["redpagos"] = Redpagos,
                ["scalapay"] = Scalapay,
                ["sepa"] = Sepa,
                ["servipag"] = Servipag,
                ["seveneleven"] = Seveneleven,
                ["sezzle"] = Sezzle,
                ["shopeepay"] = Shopeepay,
                ["singteldash"] = Singteldash,
                ["smartpay"] = Smartpay,
                ["sofort"] = Sofort,
                ["spei"] = Spei,
                ["stitch"] = Stitch,
                ["swish"] = Swish,
                ["stripe"] = Stripe,
                ["stripedd"] = Stripedd,
                ["stripetoken"] = Stripetoken,
                ["tapi"] = Tapi,
                ["tapifintechs"] = Tapifintechs,
                ["thaiqr"] = Thaiqr,
                ["touchngo"] = Touchngo,
                ["truemoney"] = Truemoney,
                ["trustly"] = Trustly,
                ["trustlyeurope"] = Trustlyeurope,
                ["upi"] = Upi,
                ["venmo"] = Venmo,
                ["vipps"] = Vipps,
                ["waave"] = Waave,
                ["webpay"] = Webpay,
                ["wechat"] = Wechat,
                ["wero"] = Wero,
                ["yape"] = Yape,
                ["zippay"] = Zippay
            };

        private static readonly ConcurrentDictionary<string, Method> _values =
            new ConcurrentDictionary<string, Method>(_knownValues);

        private Method(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Method Of(string value)
        {
            return _values.GetOrAdd(value, _ => new Method(value));
        }

        public static implicit operator Method(string value) => Of(value);
        public static implicit operator string(Method method) => method.Value;

        public static Method[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Method);

        public bool Equals(Method? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}