//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class MockCardOptions
    {
        /// <summary>
        /// Allows for mocking the merchant advice code.
        /// </summary>
        [JsonProperty("merchant_advice_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<MockCardMerchantAdviceCodeOptions?> MerchantAdviceCode { get; set; }
        public bool ShouldSerializeMerchantAdviceCode() => MerchantAdviceCode.IsSet;

        /// <summary>
        /// When set to true, prevents retries on failed transactions.
        /// </summary>
        [JsonProperty("skip_retry", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<bool?> SkipRetry { get; set; }
        public bool ShouldSerializeSkipRetry() => SkipRetry.IsSet;
    }
}