//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class NuveiKlarnaOptions
    {
        /// <summary>
        /// Additional data to be sent to Nuvei.
        /// </summary>
        [JsonProperty("customData", NullValueHandling = NullValueHandling.Include)]
        public string? CustomData
        {
            get => _customData;
            set
            {
                _customData = value;
                _customDataSet = true;
            }
        }

        private string? _customData = null;

        private bool _customDataSet = false;

        public bool ShouldSerializeCustomData() => _customDataSet;
    }
}