//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Payment Method<br/>
    /// <br/>
    /// A summary of a payment method.
    /// </summary>
    public class PaymentMethodSummary
    {
        /// <summary>
        /// Always `payment-method`.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; } = "payment-method";

        /// <summary>
        /// The optional URL that the buyer needs to be redirected to to further authorize their payment.
        /// </summary>
        [JsonProperty("approval_url")]
        public string? ApprovalUrl { get; set; } = null;

        /// <summary>
        /// The 2-letter ISO code of the country this payment method can be used for. If this value is null the payment method may be used in multiple countries.
        /// </summary>
        [JsonProperty("country")]
        public string? Country { get; set; } = null;

        /// <summary>
        /// The ISO-4217 currency code that this payment method can be used for. If this value is null the payment method may be used for multiple currencies.
        /// </summary>
        [JsonProperty("currency")]
        public string? Currency { get; set; } = null;

        /// <summary>
        /// Details for credit or debit card payment method.
        /// </summary>
        [JsonProperty("details")]
        public PaymentMethodDetailsCard? Details { get; set; } = null;

        /// <summary>
        /// The expiration date for the payment method.
        /// </summary>
        [JsonProperty("expiration_date")]
        public string? ExpirationDate { get; set; } = null;

        /// <summary>
        /// The unique hash derived from the payment method identifier (e.g. card number).
        /// </summary>
        [JsonProperty("fingerprint")]
        public string? Fingerprint { get; set; } = null;

        /// <summary>
        /// A label for the card or the account. For a paypal payment method this is the user's email address. For a card it is the last 4 digits of the card.
        /// </summary>
        [JsonProperty("label")]
        public string? Label { get; set; } = null;

        /// <summary>
        /// The date and time when this card was last replaced by the account updater.
        /// </summary>
        [JsonProperty("last_replaced_at")]
        public DateTime? LastReplacedAt { get; set; } = null;

        [JsonProperty("method")]
        public string Method { get; set; } = default!;

        /// <summary>
        /// The mode to use with this payment method.
        /// </summary>
        [JsonProperty("mode")]
        public string? Mode { get; set; } = null;

        /// <summary>
        /// The scheme of the card. Only applies to card payments.
        /// </summary>
        [JsonProperty("scheme")]
        public string? Scheme { get; set; } = null;

        /// <summary>
        /// The ID for the payment method.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The ID of the merchant account this buyer belongs to.
        /// </summary>
        [JsonProperty("merchant_account_id")]
        public string MerchantAccountId { get; set; } = default!;

        /// <summary>
        /// Additional schemes of the card besides the primary scheme. Only applies to card payment methods.
        /// </summary>
        [JsonProperty("additional_schemes")]
        public List<string>? AdditionalSchemes { get; set; } = null;

        /// <summary>
        /// The timestamp when this payment method was last used in a transaction for client initiated transactions.
        /// </summary>
        [JsonProperty("cit_last_used_at")]
        public DateTime? CitLastUsedAt { get; set; } = null;

        /// <summary>
        /// The number of times this payment method has been used in transactions for client initiated transactions.
        /// </summary>
        [JsonProperty("cit_usage_count")]
        public long CitUsageCount { get; set; } = default!;

        /// <summary>
        /// Whether this card has a pending replacement that hasn't been applied yet.
        /// </summary>
        [JsonProperty("has_replacement")]
        public bool HasReplacement { get; set; } = default!;

        /// <summary>
        /// The timestamp when this payment method was last used in a transaction.
        /// </summary>
        [JsonProperty("last_used_at")]
        public DateTime? LastUsedAt { get; set; } = null;

        /// <summary>
        /// The number of times this payment method has been used in transactions.
        /// </summary>
        [JsonProperty("usage_count")]
        public long UsageCount { get; set; } = default!;
    }
}