//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public class PaymentLinkCreate
    {
        /// <summary>
        /// The guest buyer for the payment link.
        /// </summary>
        [JsonProperty("buyer")]
        public GuestBuyer? Buyer { get; set; } = null;

        /// <summary>
        /// The expiration date and time for the payment link.
        /// </summary>
        [JsonProperty("expires_at")]
        public DateTime? ExpiresAt { get; set; } = null;

        /// <summary>
        /// Connection options for the payment link.
        /// </summary>
        [JsonProperty("connection_options")]
        public TransactionConnectionOptions? ConnectionOptions { get; set; } = null;

        /// <summary>
        /// The merchant reference for the payment link.
        /// </summary>
        [JsonProperty("external_identifier")]
        public string? ExternalIdentifier { get; set; } = null;

        /// <summary>
        /// The statement descriptor for the payment link.
        /// </summary>
        [JsonProperty("statement_descriptor")]
        public StatementDescriptor? StatementDescriptor { get; set; } = null;

        /// <summary>
        /// The locale for the payment link.
        /// </summary>
        [JsonProperty("locale")]
        public string? Locale { get; set; } = null;

        /// <summary>
        /// The merchant's display name.
        /// </summary>
        [JsonProperty("merchant_name")]
        public string? MerchantName { get; set; } = null;

        /// <summary>
        /// The merchant's website URL.
        /// </summary>
        [JsonProperty("merchant_url")]
        public string? MerchantUrl { get; set; } = null;

        /// <summary>
        /// The merchant's banner image URL.
        /// </summary>
        [JsonProperty("merchant_banner_url")]
        public string? MerchantBannerUrl { get; set; } = null;

        /// <summary>
        /// The merchant's brand color.
        /// </summary>
        [JsonProperty("merchant_color")]
        public string? MerchantColor { get; set; } = null;

        /// <summary>
        /// A message from the merchant.
        /// </summary>
        [JsonProperty("merchant_message")]
        public string? MerchantMessage { get; set; } = null;

        /// <summary>
        /// URL to the merchant's terms and conditions.
        /// </summary>
        [JsonProperty("merchant_terms_and_conditions_url")]
        public string? MerchantTermsAndConditionsUrl { get; set; } = null;

        /// <summary>
        /// URL to the merchant's favicon.
        /// </summary>
        [JsonProperty("merchant_favicon_url")]
        public string? MerchantFaviconUrl { get; set; } = null;

        /// <summary>
        /// The amount for the payment link.
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;

        /// <summary>
        /// The country code for the payment link.
        /// </summary>
        [JsonProperty("country")]
        public string Country { get; set; } = default!;

        /// <summary>
        /// The currency code for the payment link.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; } = default!;

        [JsonProperty("intent")]
        public string? Intent { get; set; }

        /// <summary>
        /// The return URL after payment completion.
        /// </summary>
        [JsonProperty("return_url")]
        public string? ReturnUrl { get; set; } = null;

        /// <summary>
        /// The cart items for the payment link.
        /// </summary>
        [JsonProperty("cart_items")]
        public List<CartItem>? CartItems { get; set; } = null;

        /// <summary>
        /// Arbitrary metadata for the payment link.
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, object>? Metadata { get; set; } = null;

        /// <summary>
        /// The way payment method information made it to this transaction.
        /// </summary>
        [JsonProperty("payment_source")]
        public string? PaymentSource { get; set; }

        /// <summary>
        /// Whether to store the payment method for future use.
        /// </summary>
        [JsonProperty("store")]
        public bool? Store { get; set; } = false;

        /// <summary>
        /// The ID of the buyer to associate the payment method with. Note: When `buyer_id` is provided, the payment link should be treated as a secret as it will allow the user to manage payment methods for the associated buyer.
        /// </summary>
        [JsonProperty("buyer_id")]
        public string? BuyerId { get; set; } = null;

        /// <summary>
        /// The number of installments a buyer is required to make.
        /// </summary>
        [JsonProperty("installment_count")]
        public long? InstallmentCount { get; set; } = null;
    }
}