//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Components
{
    using Newtonsoft.Json;
    using gr4vy.Utils;
    
    public class PaymentOptionContextApprovalUI
    {

        [JsonProperty("height")]
        public string? Height { get; set; } = null;

        [JsonProperty("width")]
        public string? Width { get; set; } = null;
    }
}