//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class PaymentMethodStoredCard
    {
        /// <summary>
        /// Set to `id` to use a stored card.
        /// </summary>
        [JsonProperty("method", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string Method { get; } = "id";

        /// <summary>
        /// The ID of the stored card to use.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;
    }
}