//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class PayoutPaymentService
    {
        /// <summary>
        /// Always `payment-service`.
        /// </summary>
        [JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string Type { get; } = "payment-service";

        /// <summary>
        /// The ID for the payout service.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> Id { get; set; }
        public bool ShouldSerializeId() => Id.IsSet;

        /// <summary>
        /// Always `card`.
        /// </summary>
        [JsonProperty("method", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string Method { get; } = "card";

        /// <summary>
        /// The ID of the connection used for this payout.
        /// </summary>
        [JsonProperty("payment_service_definition_id", Required = Newtonsoft.Json.Required.Always)]
        public string PaymentServiceDefinitionId { get; set; } = default!;

        /// <summary>
        /// The display name of the connection used for this payout.
        /// </summary>
        [JsonProperty("display_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> DisplayName { get; set; }
        public bool ShouldSerializeDisplayName() => DisplayName.IsSet;
    }
}