//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class PaypalShippingOptions
    {
        /// <summary>
        /// Shipping options that the payee or merchant offers to the payer to ship or pick up their items.
        /// </summary>
        [JsonProperty("options")]
        public List<PaypalShippingOptionsItem>? Options { get; set; } = null;
    }
}