//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    
    public class PaypalShippingOptionsItemAmount
    {

        /// <summary>
        /// The three-character ISO currency code.
        /// </summary>
        [JsonProperty("currency_code")]
        public string CurrencyCode { get; set; } = default!;

        /// <summary>
        /// The amount value, which might include a decimal portion.
        /// </summary>
        [JsonProperty("value")]
        public string Value { get; set; } = default!;
    }
}