//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class PazeEnhancedTransactionData
    {
        /// <summary>
        /// Details pertaining to electronic commerce purchases.
        /// </summary>
        [JsonProperty("ecomData")]
        public PazeEcomData? EcomData { get; set; } = null;

        /// <summary>
        /// Details pertaining to travel bookings.
        /// </summary>
        [JsonProperty("travelData")]
        public PazeTravelData? TravelData { get; set; } = null;
    }
}