//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Create a Paze transaction with a device token.
    /// </summary>
    public class PazePaymentMethodCreate
    {
        /// <summary>
        /// The external identifier of the buyer to create a payment for.
        /// </summary>
        [JsonProperty("buyer_external_identifier", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BuyerExternalIdentifier { get; set; }
        public bool ShouldSerializeBuyerExternalIdentifier() => BuyerExternalIdentifier.IsSet;

        /// <summary>
        /// The ID of the buyer to retrieve billing details for.
        /// </summary>
        [JsonProperty("buyer_id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> BuyerId { get; set; }
        public bool ShouldSerializeBuyerId() => BuyerId.IsSet;

        /// <summary>
        /// The card holder name associated to the original card for the token.
        /// </summary>
        [JsonProperty("cardholder_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> CardholderName { get; set; }
        public bool ShouldSerializeCardholderName() => CardholderName.IsSet;

        /// <summary>
        /// The URL to redirect a user back to after the complete 3DS in browser.
        /// </summary>
        [JsonProperty("redirect_url", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> RedirectUrl { get; set; }
        public bool ShouldSerializeRedirectUrl() => RedirectUrl.IsSet;

        /// <summary>
        /// The last 4 digits of the original card used to generate the token.
        /// </summary>
        [JsonProperty("card_suffix", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> CardSuffix { get; set; }
        public bool ShouldSerializeCardSuffix() => CardSuffix.IsSet;

        /// <summary>
        /// The original card scheme for which the token was generated.
        /// </summary>
        [JsonProperty("card_scheme", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> CardScheme { get; set; }
        public bool ShouldSerializeCardScheme() => CardScheme.IsSet;

        /// <summary>
        /// The payment scheme of the card.
        /// </summary>
        [JsonProperty("card_type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> CardType { get; set; }
        public bool ShouldSerializeCardType() => CardType.IsSet;

        /// <summary>
        /// Always `paze`
        /// </summary>
        [JsonProperty("method", Required = Newtonsoft.Json.Required.Always)]
        public string Method { get; } = "paze";

        /// <summary>
        /// The opaque token as received from the Paze complete response.
        /// </summary>
        [JsonProperty("token", Required = Newtonsoft.Json.Required.Always)]
        public string Token { get; set; } = default!;

        /// <summary>
        /// The signed checkout JWS as received from the Paze checkout response.
        /// </summary>
        [JsonProperty("checkout_token", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> CheckoutToken { get; set; }
        public bool ShouldSerializeCheckoutToken() => CheckoutToken.IsSet;
    }
}