//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class PazeSessionRequest
    {
        /// <summary>
        /// The platform that the Paze session is being created for. Defaults to `web`.
        /// </summary>
        [JsonProperty("source")]
        public Source? Source { get; set; } = Gr4vy.Models.Components.Source.Web;

        /// <summary>
        /// The domain on which Paze is being loaded. Required when `source` is `web`.
        /// </summary>
        [JsonProperty("domain_name")]
        public string? DomainName { get; set; } = null;
    }
}