//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Plaid Payment Method<br/>
    /// 
    /// <remarks>
    /// <br/>
    /// Plaid Payment Method to use in a transaction.
    /// </remarks>
    /// </summary>
    public class PlaidPaymentMethodCreate
    {

        /// <summary>
        /// Always `plaid`.
        /// </summary>
        [JsonProperty("method")]
        public string Method { get; } = "plaid";

        /// <summary>
        /// The public token obtained after using Plaid Link.
        /// </summary>
        [JsonProperty("token")]
        public string Token { get; set; } = default!;

        /// <summary>
        /// The Plaid account ID corresponding to the end-user account. If not provided will be fetched from Plaid API expecting to only have one.
        /// </summary>
        [JsonProperty("account_id")]
        public string? AccountId { get; set; } = null;

        /// <summary>
        /// The ID of the Plaid payment service related to the provided public token. If not provided will be fetched from the currently active expecting to have a single one.
        /// </summary>
        [JsonProperty("payment_service_id")]
        public string? PaymentServiceId { get; set; } = null;

        /// <summary>
        /// The ID of the buyer to attach the method to.
        /// </summary>
        [JsonProperty("buyer_id")]
        public string? BuyerId { get; set; } = null;

        /// <summary>
        /// The merchant reference for this payment method.
        /// </summary>
        [JsonProperty("buyer_external_identifier")]
        public string? BuyerExternalIdentifier { get; set; } = null;
    }
}