//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ProductType : IEquatable<ProductType>, IOpenEnum<string>
    {
        public static readonly ProductType Physical = new ProductType("physical");
        public static readonly ProductType Discount = new ProductType("discount");
        public static readonly ProductType ShippingFee = new ProductType("shipping_fee");
        public static readonly ProductType SalesTax = new ProductType("sales_tax");
        public static readonly ProductType Digital = new ProductType("digital");
        public static readonly ProductType GiftCard = new ProductType("gift_card");
        public static readonly ProductType StoreCredit = new ProductType("store_credit");
        public static readonly ProductType Surcharge = new ProductType("surcharge");

        private static readonly Dictionary <string, ProductType> _knownValues =
            new Dictionary <string, ProductType> ()
            {
                ["physical"] = Physical,
                ["discount"] = Discount,
                ["shipping_fee"] = ShippingFee,
                ["sales_tax"] = SalesTax,
                ["digital"] = Digital,
                ["gift_card"] = GiftCard,
                ["store_credit"] = StoreCredit,
                ["surcharge"] = Surcharge
            };

        private static readonly ConcurrentDictionary<string, ProductType> _values =
            new ConcurrentDictionary<string, ProductType>(_knownValues);

        private ProductType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ProductType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ProductType(value));
        }

        public static implicit operator ProductType(string value) => Of(value);
        public static implicit operator string(ProductType producttype) => producttype.Value;

        public static ProductType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ProductType);

        public bool Equals(ProductType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}