//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class ReportCreate
    {
        /// <summary>
        /// The name of the report.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// A description of the report.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        [JsonProperty("schedule")]
        public string Schedule { get; set; } = default!;

        /// <summary>
        /// Whether the report schedule is enabled.
        /// </summary>
        [JsonProperty("schedule_enabled")]
        public bool ScheduleEnabled { get; set; } = default!;

        /// <summary>
        /// The timezone for the report schedule.
        /// </summary>
        [JsonProperty("schedule_timezone")]
        public string? ScheduleTimezone { get; set; } = "Etc/UTC";

        /// <summary>
        /// The report specification.
        /// </summary>
        [JsonProperty("spec", NullValueHandling = NullValueHandling.Include)]
        public Spec Spec { get; set; } = default!;

        public AccountsReceivablesReportSpec? GetSpecAccountsReceivables()
        {
            return Spec.AccountsReceivablesReportSpec;
        }

        public DetailedSettlementReportSpec? GetSpecDetailedSettlement()
        {
            return Spec.DetailedSettlementReportSpec;
        }

        public TransactionRetriesReportSpec? GetSpecTransactionRetries()
        {
            return Spec.TransactionRetriesReportSpec;
        }

        public TransactionsReportSpec? GetSpecTransactions()
        {
            return Spec.TransactionsReportSpec;
        }
    }
}