//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class RyftCardOptions
    {
        /// <summary>
        /// Ryft linked sub-account ID, sent as the `Account` header.
        /// </summary>
        [JsonProperty("sub_account_id", NullValueHandling = NullValueHandling.Include)]
        public string? SubAccountId
        {
            get => _subAccountId;
            set
            {
                _subAccountId = value;
                _subAccountIdSet = true;
            }
        }

        private string? _subAccountId = null;

        private bool _subAccountIdSet = false;

        public bool ShouldSerializeSubAccountId() => _subAccountIdSet;

        /// <summary>
        /// Platform Fee in the transaction currency's smallest unit. Sent as Ryft's `platformFee` field.
        /// </summary>
        [JsonProperty("platform_fee", NullValueHandling = NullValueHandling.Include)]
        public long? PlatformFee
        {
            get => _platformFee;
            set
            {
                _platformFee = value;
                _platformFeeSet = true;
            }
        }

        private long? _platformFee = null;

        private bool _platformFeeSet = false;

        public bool ShouldSerializePlatformFee() => _platformFeeSet;
    }
}