//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class ShippingCarrier : IEquatable<ShippingCarrier>, IOpenEnum<string>
    {
        public static readonly ShippingCarrier Amazon = new ShippingCarrier("amazon");
        public static readonly ShippingCarrier Bpost = new ShippingCarrier("bpost");
        public static readonly ShippingCarrier Brt = new ShippingCarrier("brt");
        public static readonly ShippingCarrier CanadaPost = new ShippingCarrier("canada_post");
        public static readonly ShippingCarrier CeskaPosta = new ShippingCarrier("ceska_posta");
        public static readonly ShippingCarrier Dhl = new ShippingCarrier("dhl");
        public static readonly ShippingCarrier Doordash = new ShippingCarrier("doordash");
        public static readonly ShippingCarrier Dpd = new ShippingCarrier("dpd");
        public static readonly ShippingCarrier Evri = new ShippingCarrier("evri");
        public static readonly ShippingCarrier Fedex = new ShippingCarrier("fedex");
        public static readonly ShippingCarrier Gls = new ShippingCarrier("gls");
        public static readonly ShippingCarrier Inpost = new ShippingCarrier("inpost");
        public static readonly ShippingCarrier JtExpress = new ShippingCarrier("jt_express");
        public static readonly ShippingCarrier LandmarkGlobal = new ShippingCarrier("landmark_global");
        public static readonly ShippingCarrier Lasership = new ShippingCarrier("lasership");
        public static readonly ShippingCarrier Packeta = new ShippingCarrier("packeta");
        public static readonly ShippingCarrier Ppl = new ShippingCarrier("ppl");
        public static readonly ShippingCarrier Purolator = new ShippingCarrier("purolator");
        public static readonly ShippingCarrier RrDonnelley = new ShippingCarrier("rr_donnelley");
        public static readonly ShippingCarrier Sda = new ShippingCarrier("sda");
        public static readonly ShippingCarrier Ups = new ShippingCarrier("ups");
        public static readonly ShippingCarrier Usps = new ShippingCarrier("usps");
        public static readonly ShippingCarrier Veho = new ShippingCarrier("veho");
        public static readonly ShippingCarrier Other = new ShippingCarrier("other");

        private static readonly Dictionary <string, ShippingCarrier> _knownValues =
            new Dictionary <string, ShippingCarrier> ()
            {
                ["amazon"] = Amazon,
                ["bpost"] = Bpost,
                ["brt"] = Brt,
                ["canada_post"] = CanadaPost,
                ["ceska_posta"] = CeskaPosta,
                ["dhl"] = Dhl,
                ["doordash"] = Doordash,
                ["dpd"] = Dpd,
                ["evri"] = Evri,
                ["fedex"] = Fedex,
                ["gls"] = Gls,
                ["inpost"] = Inpost,
                ["jt_express"] = JtExpress,
                ["landmark_global"] = LandmarkGlobal,
                ["lasership"] = Lasership,
                ["packeta"] = Packeta,
                ["ppl"] = Ppl,
                ["purolator"] = Purolator,
                ["rr_donnelley"] = RrDonnelley,
                ["sda"] = Sda,
                ["ups"] = Ups,
                ["usps"] = Usps,
                ["veho"] = Veho,
                ["other"] = Other
            };

        private static readonly ConcurrentDictionary<string, ShippingCarrier> _values =
            new ConcurrentDictionary<string, ShippingCarrier>(_knownValues);

        private ShippingCarrier(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ShippingCarrier Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ShippingCarrier(value));
        }

        public static implicit operator ShippingCarrier(string value) => Of(value);
        public static implicit operator string(ShippingCarrier shippingcarrier) => shippingcarrier.Value;

        public static ShippingCarrier[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ShippingCarrier);

        public bool Equals(ShippingCarrier? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}