//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class StripeOptions
    {
        /// <summary>
        /// Stripe options to support Stripe Connect.
        /// </summary>
        [JsonProperty("stripe_connect", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<StripeConnectOptions?> StripeConnect { get; set; }
        public bool ShouldSerializeStripeConnect() => StripeConnect.IsSet;
    }
}