//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Indicates the frequency unit for the subscription. Allowed values are: `DAY`, `WEEK`, `MONTH`, `BI_MONTHLY`, `QUARTER`, `SEMI_ANNUALLY`, `YEAR`, `ONDEMAND`.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class SubscriptionFrequencyUnit : IEquatable<SubscriptionFrequencyUnit>, IOpenEnum<string>
    {
        public static readonly SubscriptionFrequencyUnit Month = new SubscriptionFrequencyUnit("MONTH");
        public static readonly SubscriptionFrequencyUnit Week = new SubscriptionFrequencyUnit("WEEK");
        public static readonly SubscriptionFrequencyUnit BiMonthly = new SubscriptionFrequencyUnit("BI_MONTHLY");
        public static readonly SubscriptionFrequencyUnit Ondemand = new SubscriptionFrequencyUnit("ONDEMAND");
        public static readonly SubscriptionFrequencyUnit Quarter = new SubscriptionFrequencyUnit("QUARTER");
        public static readonly SubscriptionFrequencyUnit Year = new SubscriptionFrequencyUnit("YEAR");
        public static readonly SubscriptionFrequencyUnit SemiAnnually = new SubscriptionFrequencyUnit("SEMI_ANNUALLY");
        public static readonly SubscriptionFrequencyUnit Day = new SubscriptionFrequencyUnit("DAY");

        private static readonly Dictionary <string, SubscriptionFrequencyUnit> _knownValues =
            new Dictionary <string, SubscriptionFrequencyUnit> ()
            {
                ["MONTH"] = Month,
                ["WEEK"] = Week,
                ["BI_MONTHLY"] = BiMonthly,
                ["ONDEMAND"] = Ondemand,
                ["QUARTER"] = Quarter,
                ["YEAR"] = Year,
                ["SEMI_ANNUALLY"] = SemiAnnually,
                ["DAY"] = Day
            };

        private static readonly ConcurrentDictionary<string, SubscriptionFrequencyUnit> _values =
            new ConcurrentDictionary<string, SubscriptionFrequencyUnit>(_knownValues);

        private SubscriptionFrequencyUnit(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static SubscriptionFrequencyUnit Of(string value)
        {
            return _values.GetOrAdd(value, _ => new SubscriptionFrequencyUnit(value));
        }

        public static implicit operator SubscriptionFrequencyUnit(string value) => Of(value);
        public static implicit operator string(SubscriptionFrequencyUnit subscriptionfrequencyunit) => subscriptionfrequencyunit.Value;

        public static SubscriptionFrequencyUnit[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as SubscriptionFrequencyUnit);

        public bool Equals(SubscriptionFrequencyUnit? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}