//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class TaxId
    {
        /// <summary>
        /// The tax ID for the buyer.
        /// </summary>
        [JsonProperty("value")]
        public string Value { get; set; } = default!;

        [JsonProperty("kind")]
        public string Kind { get; set; } = default!;
    }
}