//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class ThreeDSecureScenarioOutcome
    {
        /// <summary>
        /// The version of 3DS which will be simulated.
        /// </summary>
        [JsonProperty("version", NullValueHandling = NullValueHandling.Include)]
        public string? Version
        {
            get => _version;
            set
            {
                _version = value;
                _versionSet = true;
            }
        }

        private string? _version = null;

        private bool _versionSet = false;

        public bool ShouldSerializeVersion() => _versionSet;

        [JsonProperty("authentication", NullValueHandling = NullValueHandling.Include)]
        public ThreeDSecureScenarioOutcomeAuthentication Authentication
        {
            get => _authentication;
            set
            {
                _authentication = value;
                _authenticationSet = true;
            }
        }

        private ThreeDSecureScenarioOutcomeAuthentication _authentication = default!;

        private bool _authenticationSet = true;

        public bool ShouldSerializeAuthentication() => _authenticationSet;

        /// <summary>
        /// 3DS result value. Required if authentication status is "C".
        /// </summary>
        [JsonProperty("result", NullValueHandling = NullValueHandling.Include)]
        public ThreeDSecureScenarioOutcomeResult? Result
        {
            get => _result;
            set
            {
                _result = value;
                _resultSet = true;
            }
        }

        private ThreeDSecureScenarioOutcomeResult? _result = null;

        private bool _resultSet = false;

        public bool ShouldSerializeResult() => _resultSet;
    }
}