//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;

    public class ThreeDSecureScenario
    {
        /// <summary>
        /// Always `three-d-secure-scenario`.
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; } = "three-d-secure-scenario";

        /// <summary>
        /// Unique identifier for the 3DS scenario.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// ID of the associated merchant account.
        /// </summary>
        [JsonProperty("merchant_account_id")]
        public string MerchantAccountId { get; set; } = default!;

        /// <summary>
        /// The date and time when this 3DS scenario was first created in our system.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; } = default!;

        /// <summary>
        /// The date and time when this 3DS scenario was last updated in our system.
        /// </summary>
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; } = default!;

        [JsonProperty("conditions")]
        public ThreeDSecureScenarioConditions Conditions { get; set; } = default!;

        [JsonProperty("outcome")]
        public ThreeDSecureScenarioOutcome Outcome { get; set; } = default!;
    }
}