//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class ThreeDSecureScenarioUpdate
    {
        /// <summary>
        /// Conditions for the scenario.
        /// </summary>
        [JsonProperty("conditions", NullValueHandling = NullValueHandling.Include)]
        public ThreeDSecureScenarioConditions? Conditions
        {
            get => _conditions;
            set
            {
                _conditions = value;
                _conditionsSet = true;
            }
        }

        private ThreeDSecureScenarioConditions? _conditions = null;

        private bool _conditionsSet = false;

        public bool ShouldSerializeConditions() => _conditionsSet;

        /// <summary>
        /// Outcome for the scenario.
        /// </summary>
        [JsonProperty("outcome", NullValueHandling = NullValueHandling.Include)]
        public ThreeDSecureScenarioOutcome? Outcome
        {
            get => _outcome;
            set
            {
                _outcome = value;
                _outcomeSet = true;
            }
        }

        private ThreeDSecureScenarioOutcome? _outcome = null;

        private bool _outcomeSet = false;

        public bool ShouldSerializeOutcome() => _outcomeSet;
    }
}