//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class ThreeDSecureScenarioConditions
    {
        /// <summary>
        /// First name of the buyer to match.
        /// </summary>
        [JsonProperty("first_name", NullValueHandling = NullValueHandling.Include)]
        public string? FirstName
        {
            get => _firstName;
            set
            {
                _firstName = value;
                _firstNameSet = true;
            }
        }

        private string? _firstName = null;

        private bool _firstNameSet = false;

        public bool ShouldSerializeFirstName() => _firstNameSet;

        /// <summary>
        /// Last name of the buyer to match.
        /// </summary>
        [JsonProperty("last_name", NullValueHandling = NullValueHandling.Include)]
        public string? LastName
        {
            get => _lastName;
            set
            {
                _lastName = value;
                _lastNameSet = true;
            }
        }

        private string? _lastName = null;

        private bool _lastNameSet = false;

        public bool ShouldSerializeLastName() => _lastNameSet;

        /// <summary>
        /// Email address of the buyer to match.
        /// </summary>
        [JsonProperty("email_address", NullValueHandling = NullValueHandling.Include)]
        public string? EmailAddress
        {
            get => _emailAddress;
            set
            {
                _emailAddress = value;
                _emailAddressSet = true;
            }
        }

        private string? _emailAddress = null;

        private bool _emailAddressSet = false;

        public bool ShouldSerializeEmailAddress() => _emailAddressSet;

        /// <summary>
        /// Amount of the transaction to match.
        /// </summary>
        [JsonProperty("amount", NullValueHandling = NullValueHandling.Include)]
        public long? Amount
        {
            get => _amount;
            set
            {
                _amount = value;
                _amountSet = true;
            }
        }

        private long? _amount = null;

        private bool _amountSet = false;

        public bool ShouldSerializeAmount() => _amountSet;

        /// <summary>
        /// External identifier to match.
        /// </summary>
        [JsonProperty("external_identifier", NullValueHandling = NullValueHandling.Include)]
        public string? ExternalIdentifier
        {
            get => _externalIdentifier;
            set
            {
                _externalIdentifier = value;
                _externalIdentifierSet = true;
            }
        }

        private string? _externalIdentifier = null;

        private bool _externalIdentifierSet = false;

        public bool ShouldSerializeExternalIdentifier() => _externalIdentifierSet;

        /// <summary>
        /// Card number to match.
        /// </summary>
        [JsonProperty("card_number", NullValueHandling = NullValueHandling.Include)]
        public string? CardNumber
        {
            get => _cardNumber;
            set
            {
                _cardNumber = value;
                _cardNumberSet = true;
            }
        }

        private string? _cardNumber = null;

        private bool _cardNumberSet = false;

        public bool ShouldSerializeCardNumber() => _cardNumberSet;
    }
}