//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    
    public class ThreeDSecureScenarioConditions
    {

        /// <summary>
        /// First name of the buyer to match.
        /// </summary>
        [JsonProperty("first_name")]
        public string? FirstName { get; set; } = null;

        /// <summary>
        /// Last name of the buyer to match.
        /// </summary>
        [JsonProperty("last_name")]
        public string? LastName { get; set; } = null;

        /// <summary>
        /// Email address of the buyer to match.
        /// </summary>
        [JsonProperty("email_address")]
        public string? EmailAddress { get; set; } = null;

        /// <summary>
        /// Amount of the transaction to match.
        /// </summary>
        [JsonProperty("amount")]
        public long? Amount { get; set; } = null;

        /// <summary>
        /// External identifier to match.
        /// </summary>
        [JsonProperty("external_identifier")]
        public string? ExternalIdentifier { get; set; } = null;

        /// <summary>
        /// Card number to match.
        /// </summary>
        [JsonProperty("card_number")]
        public string? CardNumber { get; set; } = null;
    }
}