//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    
    public class ThreeDSecure
    {

        /// <summary>
        /// The amount to be used for 3DS authentication. Optionally set this value to authenticate a greater amount than the transaction amount.
        /// </summary>
        [JsonProperty("amount")]
        public long? Amount { get; set; } = null;
    }
}