//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class TransactionPaymentService
    {
        /// <summary>
        /// Always `payment-service`.
        /// </summary>
        [JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string Type { get; } = "payment-service";

        /// <summary>
        /// The ID for the payment-service.
        /// </summary>
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The definition ID of the service used to process this payment.
        /// </summary>
        [JsonProperty("payment_service_definition_id", Required = Newtonsoft.Json.Required.Always)]
        public string PaymentServiceDefinitionId { get; set; } = default!;

        [JsonProperty("method", Required = Newtonsoft.Json.Required.Always)]
        public string Method { get; set; } = default!;

        /// <summary>
        /// The display name for the payment service.
        /// </summary>
        [JsonProperty("display_name", Required = Newtonsoft.Json.Required.Always)]
        public string DisplayName { get; set; } = default!;
    }
}