//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Request body for capturing an authorized transaction.
    /// </summary>
    public class TransactionCaptureCreate
    {
        /// <summary>
        /// The amount to capture, in the smallest currency unit (e.g., cents). This must be less than or equal to the authorized amount, unless over-capture is available.
        /// </summary>
        [JsonProperty("amount")]
        public long? Amount { get; set; } = null;

        /// <summary>
        /// The airline data to submit to the payment service during the capture call.
        /// </summary>
        [JsonProperty("airline")]
        public Airline? Airline { get; set; } = null;
    }
}