//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The way payment method information made it to this transaction.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class TransactionPaymentSource : IEquatable<TransactionPaymentSource>, IOpenEnum<string>
    {
        public static readonly TransactionPaymentSource Ecommerce = new TransactionPaymentSource("ecommerce");
        public static readonly TransactionPaymentSource Moto = new TransactionPaymentSource("moto");
        public static readonly TransactionPaymentSource Recurring = new TransactionPaymentSource("recurring");
        public static readonly TransactionPaymentSource Installment = new TransactionPaymentSource("installment");
        public static readonly TransactionPaymentSource CardOnFile = new TransactionPaymentSource("card_on_file");

        private static readonly Dictionary <string, TransactionPaymentSource> _knownValues =
            new Dictionary <string, TransactionPaymentSource> ()
            {
                ["ecommerce"] = Ecommerce,
                ["moto"] = Moto,
                ["recurring"] = Recurring,
                ["installment"] = Installment,
                ["card_on_file"] = CardOnFile
            };

        private static readonly ConcurrentDictionary<string, TransactionPaymentSource> _values =
            new ConcurrentDictionary<string, TransactionPaymentSource>(_knownValues);

        private TransactionPaymentSource(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static TransactionPaymentSource Of(string value)
        {
            return _values.GetOrAdd(value, _ => new TransactionPaymentSource(value));
        }

        public static implicit operator TransactionPaymentSource(string value) => Of(value);
        public static implicit operator string(TransactionPaymentSource transactionpaymentsource) => transactionpaymentsource.Value;

        public static TransactionPaymentSource[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as TransactionPaymentSource);

        public bool Equals(TransactionPaymentSource? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}