//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class VerifyCredentials
    {
        /// <summary>
        /// The ID of the payment service definition to verify the fields against.
        /// </summary>
        [JsonProperty("payment_service_definition_id", Required = Newtonsoft.Json.Required.Always)]
        public string PaymentServiceDefinitionId { get; set; } = default!;

        /// <summary>
        /// The optional ID of the configured payment service. New fields will be merged with any existing fields already stored before they are verified.
        /// </summary>
        [JsonProperty("payment_service_id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = NullValueHandling.Include)]
        public OptionalNullable<string?> PaymentServiceId { get; set; }
        public bool ShouldSerializePaymentServiceId() => PaymentServiceId.IsSet;

        /// <summary>
        /// The fields and their values, or a set of updated fields to merge with existing values.
        /// </summary>
        [JsonProperty("fields", Required = Newtonsoft.Json.Required.Always)]
        public List<Field> Fields { get; set; } = default!;
    }
}