//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class WpayPaytoOptions
    {
        /// <summary>
        /// Options to pass to the `instrument` resource in the Wpay PayTo API.
        /// </summary>
        [JsonProperty("instrument")]
        public WpayPaytoResourceOptions? Instrument { get; set; } = null;

        /// <summary>
        /// Options to pass to the `payment` resource in the Wpay PayTo API.
        /// </summary>
        [JsonProperty("payment")]
        public WpayPaytoResourceOptions? Payment { get; set; } = null;

        /// <summary>
        /// Options to pass to the `refund` resource in the Wpay PayTo API.
        /// </summary>
        [JsonProperty("refund")]
        public WpayPaytoResourceOptions? Refund { get; set; } = null;
    }
}