//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class WpayPaytoSimulationOptions
    {
        /// <summary>
        /// The simulation being requested. Please refer to the developer guide for a list of all available simulations.
        /// </summary>
        [JsonProperty("simulate", NullValueHandling = NullValueHandling.Include)]
        public string? Simulate
        {
            get => _simulate;
            set
            {
                _simulate = value;
                _simulateSet = true;
            }
        }

        private string? _simulate = null;

        private bool _simulateSet = false;

        public bool ShouldSerializeSimulate() => _simulateSet;

        /// <summary>
        /// The delay in seconds before the requested simulation is executed.
        /// </summary>
        [JsonProperty("delay", NullValueHandling = NullValueHandling.Include)]
        public long? Delay
        {
            get => _delay;
            set
            {
                _delay = value;
                _delaySet = true;
            }
        }

        private long? _delay = null;

        private bool _delaySet = false;

        public bool ShouldSerializeDelay() => _delaySet;
    }
}