//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class WpayEverdaypayOptions
    {

        /// <summary>
        /// A dictionary of merchant defined data, to be passed to Wpay for anti-fraud control.
        /// </summary>
        [JsonProperty("merchant_defined_data")]
        public Dictionary<string, string>? MerchantDefinedData { get; set; } = null;

        /// <summary>
        /// The customer ID for the Everyday Rewards account.
        /// </summary>
        [JsonProperty("customerId")]
        public string? CustomerId { get; set; } = null;

        /// <summary>
        /// The access token for the Everyday Rewards account.
        /// </summary>
        [JsonProperty("rewardsAccessToken")]
        public string? RewardsAccessToken { get; set; } = null;

        /// <summary>
        /// The ID of the device on which the payment is occuring.
        /// </summary>
        [JsonProperty("deviceId")]
        public string? DeviceId { get; set; } = null;

        /// <summary>
        /// Whether the transaction should redirect post-payment
        /// </summary>
        [JsonProperty("postPaymentRedirect")]
        public bool? PostPaymentRedirect { get; set; } = null;
    }
}