//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Components
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;

    public class WpayPaytoOptions
    {
        /// <summary>
        /// Options to pass to the `instrument` resource in the Wpay PayTo API.
        /// </summary>
        [JsonProperty("instrument", NullValueHandling = NullValueHandling.Include)]
        public WpayPaytoResourceOptions? Instrument
        {
            get => _instrument;
            set
            {
                _instrument = value;
                _instrumentSet = true;
            }
        }

        private WpayPaytoResourceOptions? _instrument = null;

        private bool _instrumentSet = false;

        public bool ShouldSerializeInstrument() => _instrumentSet;

        /// <summary>
        /// Options to pass to the `payment` resource in the Wpay PayTo API.
        /// </summary>
        [JsonProperty("payment", NullValueHandling = NullValueHandling.Include)]
        public WpayPaytoResourceOptions? Payment
        {
            get => _payment;
            set
            {
                _payment = value;
                _paymentSet = true;
            }
        }

        private WpayPaytoResourceOptions? _payment = null;

        private bool _paymentSet = false;

        public bool ShouldSerializePayment() => _paymentSet;

        /// <summary>
        /// Options to pass to the `refund` resource in the Wpay PayTo API.
        /// </summary>
        [JsonProperty("refund", NullValueHandling = NullValueHandling.Include)]
        public WpayPaytoResourceOptions? Refund
        {
            get => _refund;
            set
            {
                _refund = value;
                _refundSet = true;
            }
        }

        private WpayPaytoResourceOptions? _refund = null;

        private bool _refundSet = false;

        public bool ShouldSerializeRefund() => _refundSet;
    }
}