//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Requests
{
    using System.Collections.Generic;
    using gr4vy.Utils;
    
    public class CreatePaymentServiceDefinitionSessionRequest
    {

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=payment_service_definition_id")]
        public string PaymentServiceDefinitionId { get; set; } = default!;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public Dictionary<string, object> RequestBody { get; set; } = default!;
    }
}