//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Requests
{
    using Gr4vy.Utils;

    public class ListThreeDsConfigurationsRequest
    {
        /// <summary>
        /// The ID of the merchant account.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=merchant_account_id")]
        public string MerchantAccountId { get; set; } = default!;

        /// <summary>
        /// ISO 4217 currency code (3 characters) to filter 3DS configurations.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=currency")]
        public string? Currency { get; set; } = null;
    }
}