//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Requests
{
    using Gr4vy.Utils;
    
    public class ListMerchantAccountsRequest
    {

        /// <summary>
        /// A pointer to the page of results to return.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=cursor")]
        public string? Cursor { get; set; } = null;

        /// <summary>
        /// The maximum number of items that are at returned.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 20;

        /// <summary>
        /// The search term to filter merchant accounts by.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=search")]
        public string? Search { get; set; } = null;
    }
}