//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Requests
{
    using gr4vy.Models.Requests;
    using gr4vy.Utils;
    
    public class ListBuyerPaymentMethodsRequest
    {

        /// <summary>
        /// The ID of the buyer to query payment methods for.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=buyer_id")]
        public string? BuyerId { get; set; } = null;

        /// <summary>
        /// The external identifier of the buyer to query payment methods for.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=buyer_external_identifier")]
        public string? BuyerExternalIdentifier { get; set; } = null;

        /// <summary>
        /// The field to sort the payment methods by.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort_by")]
        public string? SortBy { get; } = "last_used_at";

        /// <summary>
        /// The direction to sort the payment methods in.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=order_by")]
        public OrderBy? OrderBy { get; set; } = gr4vy.Models.Requests.OrderBy.Desc;

        /// <summary>
        /// The country code to filter payment methods by. This only applies to payment methods with a `country` value.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=country")]
        public string? Country { get; set; } = null;

        /// <summary>
        /// The currency code to filter payment methods by. This only applies to payment methods with a `currency` value.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=currency")]
        public string? Currency { get; set; } = null;

        /// <summary>
        /// The ID of the merchant account to use for this request.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-gr4vy-merchant-account-id")]
        public string? MerchantAccountId { get; set; }
    }
}