//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Gr4vy.Models.Requests
{
    using Gr4vy.Models.Components;
    using Gr4vy.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class ResponseCaptureTransactionType
    {
        private ResponseCaptureTransactionType(string value) { Value = value; }

        public string Value { get; private set; }

        public static ResponseCaptureTransactionType TransactionOutput { get { return new ResponseCaptureTransactionType("Transaction-Output"); } }

        public static ResponseCaptureTransactionType TransactionCaptureOutput { get { return new ResponseCaptureTransactionType("TransactionCapture-Output"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ResponseCaptureTransactionType v) { return v.Value; }
        public static ResponseCaptureTransactionType FromString(string v) {
            switch(v) {
                case "Transaction-Output": return TransactionOutput;
                case "TransactionCapture-Output": return TransactionCaptureOutput;
                default: throw new ArgumentException("Invalid value for ResponseCaptureTransactionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ResponseCaptureTransactionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Successful Response
    /// </summary>
    [JsonConverter(typeof(ResponseCaptureTransaction.ResponseCaptureTransactionConverter))]
    public class ResponseCaptureTransaction
    {
        public ResponseCaptureTransaction(ResponseCaptureTransactionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public TransactionOutput? TransactionOutput { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public TransactionCaptureOutput? TransactionCaptureOutput { get; set; }

        public ResponseCaptureTransactionType Type { get; set; }
        public static ResponseCaptureTransaction CreateTransactionOutput(TransactionOutput transactionOutput)
        {
            ResponseCaptureTransactionType typ = ResponseCaptureTransactionType.TransactionOutput;

            ResponseCaptureTransaction res = new ResponseCaptureTransaction(typ);
            res.TransactionOutput = transactionOutput;
            return res;
        }
        public static ResponseCaptureTransaction CreateTransactionCaptureOutput(TransactionCaptureOutput transactionCaptureOutput)
        {
            ResponseCaptureTransactionType typ = ResponseCaptureTransactionType.TransactionCaptureOutput;

            ResponseCaptureTransaction res = new ResponseCaptureTransaction(typ);
            res.TransactionCaptureOutput = transactionCaptureOutput;
            return res;
        }

        public class ResponseCaptureTransactionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(ResponseCaptureTransaction);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new ResponseCaptureTransaction(ResponseCaptureTransactionType.TransactionCaptureOutput)
                    {
                        TransactionCaptureOutput = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<TransactionCaptureOutput>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(TransactionCaptureOutput), new ResponseCaptureTransaction(ResponseCaptureTransactionType.TransactionCaptureOutput), "TransactionCaptureOutput"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new ResponseCaptureTransaction(ResponseCaptureTransactionType.TransactionOutput)
                    {
                        TransactionOutput = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<TransactionOutput>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(TransactionOutput), new ResponseCaptureTransaction(ResponseCaptureTransactionType.TransactionOutput), "TransactionOutput"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                ResponseCaptureTransaction res = (ResponseCaptureTransaction)value;

                if (res.TransactionOutput != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TransactionOutput));
                    return;
                }

                if (res.TransactionCaptureOutput != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TransactionCaptureOutput));
                    return;
                }
            }

        }

    }
}