//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace gr4vy.Models.Requests
{
    using gr4vy.Models.Components;
    using gr4vy.Utils;
    
    public class UpdateDigitalWalletRequest
    {

        /// <summary>
        /// The ID of the digital wallet to edit.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=digital_wallet_id")]
        public string DigitalWalletId { get; set; } = default!;

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=timeout_in_seconds")]
        public double? TimeoutInSeconds { get; set; } = 1D;

        /// <summary>
        /// The ID of the merchant account to use for this request.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-gr4vy-merchant-account-id")]
        public string? MerchantAccountId { get; set; } = null;

        [SpeakeasyMetadata("request:mediaType=application/json")]
        public DigitalWalletUpdate DigitalWalletUpdate { get; set; } = default!;
    }
}