workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    -OAS:
        inputs:
            - location: registry.speakeasyapi.dev/gr4vy/gr4vy/openapi:main
        registry:
            location: registry.speakeasyapi.dev/gr4vy/gr4vy/-oas
targets:
    gr-4-vy:
        target: csharp
        source: -OAS
        publish:
            nuget:
                apiKey: $nuget_api_key
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gr4vy/gr4vy/-oas-csharp-code-samples
            labelOverride:
                fixedValue: Csharp (SDK)
            blocking: false
